import type { ProbeTemplates } from "./render";

export function renderCTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      'agent_debug_emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_JSON_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    dataEncoding: "serialized-json",
    helperTemplate: [
      "// #region agent log",
      "#define _POSIX_C_SOURCE 200809L",
      "#include <stdio.h>",
      "#include <string.h>",
      "#include <time.h>",
      "#ifndef _WIN32",
      "#include <fcntl.h>",
      "#include <unistd.h>",
      "#endif",
      "",
      "typedef struct {",
      "    char *buffer;",
      "    size_t length;",
      "    size_t capacity;",
      "    int overflow;",
      "} AgentDebugBuffer;",
      "",
      "static void agent_debug_append(AgentDebugBuffer *buf, const char *text, size_t n) {",
      "    if (buf->overflow) {",
      "        return;",
      "    }",
      "    if (n > buf->capacity - buf->length) {",
      "        buf->overflow = 1;",
      "        return;",
      "    }",
      "    memcpy(buf->buffer + buf->length, text, n);",
      "    buf->length += n;",
      "}",
      "",
      "static void agent_debug_append_char(AgentDebugBuffer *buf, char c) {",
      "    agent_debug_append(buf, &c, 1);",
      "}",
      "",
      "static void agent_debug_write_string(AgentDebugBuffer *buf, const char *text) {",
      "    char backslash = (char)0x5C;",
      "    char quote = (char)0x22;",
      "    agent_debug_append_char(buf, quote);",
      "    if (text != NULL) {",
      "        for (const unsigned char *p = (const unsigned char *)text; *p != 0; p += 1) {",
      "            unsigned int code = (unsigned int)(*p);",
      "            char c = (char)(*p);",
      "            if (c == quote) {",
      "                agent_debug_append_char(buf, backslash);",
      "                agent_debug_append_char(buf, quote);",
      "            } else if (c == backslash) {",
      "                agent_debug_append_char(buf, backslash);",
      "                agent_debug_append_char(buf, backslash);",
      "            } else if (code == 8 || code == 9 || code == 10 || code == 12 || code == 13) {",
      '                const char *escapes = "btn\\0fr";',
      "                agent_debug_append_char(buf, backslash);",
      "                agent_debug_append_char(buf, escapes[code - 8]);",
      "            } else if (code < 32) {",
      '                const char *digits = "0123456789abcdef";',
      "                agent_debug_append_char(buf, backslash);",
      "                agent_debug_append_char(buf, 'u');",
      "                agent_debug_append_char(buf, '0');",
      "                agent_debug_append_char(buf, '0');",
      "                agent_debug_append_char(buf, digits[(code >> 4) & 15]);",
      "                agent_debug_append_char(buf, digits[code & 15]);",
      "            } else {",
      "                agent_debug_append_char(buf, c);",
      "            }",
      "        }",
      "    }",
      "    agent_debug_append_char(buf, quote);",
      "}",
      "",
      "// Returns a pointer to a shared static buffer; not thread-safe.",
      "static const char *agent_debug_json_string(const char *text) {",
      "    static char storage[65536 + 4096];",
      "    AgentDebugBuffer buf;",
      "    buf.buffer = storage;",
      "    buf.length = 0;",
      "    buf.capacity = sizeof(storage) - 1;",
      "    buf.overflow = 0;",
      "    agent_debug_write_string(&buf, text);",
      "    storage[buf.length] = 0;",
      "    return storage;",
      "}",
      "",
      "static long long agent_debug_timestamp_ms(void) {",
      "#ifdef _WIN32",
      "    return (long long)time(NULL) * 1000;",
      "#else",
      "    struct timespec ts;",
      "    if (clock_gettime(CLOCK_REALTIME, &ts) != 0) {",
      "        return 0;",
      "    }",
      "    return (long long)ts.tv_sec * 1000 + (long long)ts.tv_nsec / 1000000;",
      "#endif",
      "}",
      "",
      "static void agent_debug_emit(const char *hypothesis_id, const char *location,",
      "                             const char *message, const char *data_json) {",
      "    if (data_json == NULL || data_json[0] == 0) {",
      "        return;",
      "    }",
      "    for (const unsigned char *scan = (const unsigned char *)data_json; *scan != 0; scan += 1) {",
      "        if (*scan < 0x20) {",
      "            return;",
      "        }",
      "    }",
      "    char storage[65536 + 4096];",
      "    AgentDebugBuffer buf;",
      "    buf.buffer = storage;",
      "    buf.length = 0;",
      "    buf.capacity = sizeof(storage);",
      "    buf.overflow = 0;",
      "    char timestamp[32];",
      '    int stamped = snprintf(timestamp, sizeof(timestamp), "%lld", agent_debug_timestamp_ms());',
      "    if (stamped < 0) {",
      "        return;",
      "    }",
      "    agent_debug_append_char(&buf, '{');",
      '    agent_debug_write_string(&buf, "hypothesisId");',
      "    agent_debug_append_char(&buf, ':');",
      "    agent_debug_write_string(&buf, hypothesis_id);",
      "    agent_debug_append_char(&buf, ',');",
      '    agent_debug_write_string(&buf, "location");',
      "    agent_debug_append_char(&buf, ':');",
      "    agent_debug_write_string(&buf, location);",
      "    agent_debug_append_char(&buf, ',');",
      '    agent_debug_write_string(&buf, "message");',
      "    agent_debug_append_char(&buf, ':');",
      "    agent_debug_write_string(&buf, message);",
      "    agent_debug_append_char(&buf, ',');",
      '    agent_debug_write_string(&buf, "data");',
      "    agent_debug_append_char(&buf, ':');",
      "    agent_debug_append(&buf, data_json, strlen(data_json));",
      "    agent_debug_append_char(&buf, ',');",
      '    agent_debug_write_string(&buf, "timestamp");',
      "    agent_debug_append_char(&buf, ':');",
      "    agent_debug_append(&buf, timestamp, (size_t)stamped);",
      "    agent_debug_append_char(&buf, '}');",
      "    agent_debug_append_char(&buf, (char)0x0A);",
      "    if (buf.overflow || buf.length > 65536) {",
      "        return;",
      "    }",
      "#ifdef _WIN32",
      '    FILE *file = fopen("__APPEND_PATH__", "ab");',
      "    if (file != NULL) {",
      "        size_t wrote = fwrite(storage, 1, buf.length, file);",
      "        (void)wrote;",
      "        fclose(file);",
      "    }",
      "#else",
      '    int fd = open("__APPEND_PATH__", O_WRONLY | O_APPEND | O_CREAT, 0600);',
      "    if (fd >= 0) {",
      "        ssize_t wrote = write(fd, storage, buf.length);",
      "        (void)wrote;",
      "        close(fd);",
      "    }",
      "#endif",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "c",
    placement: { call: "statement", helper: "file-start" },
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_JSON_EXPRESSION__:
        "Replace with an expression that returns one complete valid JSON value containing no secrets. Use the application's serializer when available; otherwise pass agent_debug_json_string(text).",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
