import type { ProbeTemplates } from "./render";

export function renderCTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      '__agentDebugEmit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "#define _POSIX_C_SOURCE 200809L",
      "#include <math.h>",
      "#include <stdarg.h>",
      "#include <stdio.h>",
      "#include <stdlib.h>",
      "#include <string.h>",
      "#include <time.h>",
      "#ifndef _WIN32",
      "#include <fcntl.h>",
      "#include <unistd.h>",
      "#endif",
      "",
      "enum {",
      "    AGENT_KIND_NULL,",
      "    AGENT_KIND_BOOL,",
      "    AGENT_KIND_INT,",
      "    AGENT_KIND_DOUBLE,",
      "    AGENT_KIND_STR,",
      "    AGENT_KIND_ARRAY,",
      "    AGENT_KIND_OBJECT",
      "};",
      "",
      "typedef struct AgentValue AgentValue;",
      "struct AgentValue {",
      "    int kind;",
      "    int boolValue;",
      "    long long intValue;",
      "    double doubleValue;",
      "    char *strValue;",
      "    char **keys;",
      "    AgentValue **items;",
      "    size_t count;",
      "};",
      "",
      "typedef struct {",
      "    char *buffer;",
      "    size_t length;",
      "    size_t capacity;",
      "    int overflow;",
      "} AgentDebugBuffer;",
      "",
      "static const char *const AGENT_DEBUG_SECRET_KEYS[] = {",
      '    "authorization", "authorization_header", "cookie", "set_cookie",',
      '    "password", "passwd", "pwd", "private_key", "secret", "token",',
      '    "credential", "credentials"};',
      "",
      "static const char *const AGENT_DEBUG_SECRET_SUFFIXES[] = {",
      '    "api_key", "api_token", "oauth_token", "o_auth_token", "private_key",',
      '    "client_secret", "access_token", "refresh_token", "id_token",',
      '    "auth_token", "bearer_token"};',
      "",
      "static AgentValue *__agent_debug_new(int kind) {",
      "    AgentValue *value = (AgentValue *)malloc(sizeof(AgentValue));",
      "    if (value == NULL) {",
      "        return NULL;",
      "    }",
      "    value->kind = kind;",
      "    value->boolValue = 0;",
      "    value->intValue = 0;",
      "    value->doubleValue = 0.0;",
      "    value->strValue = NULL;",
      "    value->keys = NULL;",
      "    value->items = NULL;",
      "    value->count = 0;",
      "    return value;",
      "}",
      "",
      "static char *__agent_debug_strdup(const char *text) {",
      "    if (text == NULL) {",
      "        return NULL;",
      "    }",
      "    size_t n = strlen(text);",
      "    char *copy = (char *)malloc(n + 1);",
      "    if (copy == NULL) {",
      "        return NULL;",
      "    }",
      "    for (size_t i = 0; i <= n; i += 1) {",
      "        copy[i] = text[i];",
      "    }",
      "    return copy;",
      "}",
      "",
      "static void __agent_debug_free(AgentValue *value) {",
      "    if (value == NULL) {",
      "        return;",
      "    }",
      "    if (value->strValue != NULL) {",
      "        free(value->strValue);",
      "    }",
      "    if (value->keys != NULL) {",
      "        for (size_t i = 0; i < value->count; i += 1) {",
      "            if (value->keys[i] != NULL) {",
      "                free(value->keys[i]);",
      "            }",
      "        }",
      "        free(value->keys);",
      "    }",
      "    if (value->items != NULL) {",
      "        for (size_t i = 0; i < value->count; i += 1) {",
      "            __agent_debug_free(value->items[i]);",
      "        }",
      "        free(value->items);",
      "    }",
      "    free(value);",
      "}",
      "",
      "static AgentValue *adbg_null(void) {",
      "    return __agent_debug_new(AGENT_KIND_NULL);",
      "}",
      "",
      "static AgentValue *adbg_bool(int flag) {",
      "    AgentValue *value = __agent_debug_new(AGENT_KIND_BOOL);",
      "    if (value != NULL) {",
      "        value->boolValue = flag ? 1 : 0;",
      "    }",
      "    return value;",
      "}",
      "",
      "static AgentValue *adbg_int(long long number) {",
      "    AgentValue *value = __agent_debug_new(AGENT_KIND_INT);",
      "    if (value != NULL) {",
      "        value->intValue = number;",
      "    }",
      "    return value;",
      "}",
      "",
      "static AgentValue *adbg_double(double number) {",
      "    AgentValue *value = __agent_debug_new(AGENT_KIND_DOUBLE);",
      "    if (value != NULL) {",
      "        value->doubleValue = number;",
      "    }",
      "    return value;",
      "}",
      "",
      "static AgentValue *adbg_str(const char *text) {",
      "    AgentValue *value = __agent_debug_new(AGENT_KIND_STR);",
      "    if (value != NULL) {",
      "        value->strValue = __agent_debug_strdup(text);",
      "    }",
      "    return value;",
      "}",
      "",
      "static AgentValue *adbg_arr(AgentValue *first, ...) {",
      "    AgentValue *value = __agent_debug_new(AGENT_KIND_ARRAY);",
      "    va_list args;",
      "    va_start(args, first);",
      "    AgentValue *current = first;",
      "    while (current != NULL) {",
      "        if (value != NULL) {",
      "            AgentValue **grown = (AgentValue **)realloc(value->items, (value->count + 1) * sizeof(AgentValue *));",
      "            if (grown != NULL) {",
      "                value->items = grown;",
      "                value->items[value->count] = current;",
      "                value->count += 1;",
      "            } else {",
      "                __agent_debug_free(current);",
      "            }",
      "        } else {",
      "            __agent_debug_free(current);",
      "        }",
      "        current = va_arg(args, AgentValue *);",
      "    }",
      "    va_end(args);",
      "    return value;",
      "}",
      "",
      "static AgentValue *adbg_obj(const char *first_key, ...) {",
      "    AgentValue *value = __agent_debug_new(AGENT_KIND_OBJECT);",
      "    va_list args;",
      "    va_start(args, first_key);",
      "    const char *key = first_key;",
      "    while (key != NULL) {",
      "        AgentValue *child = va_arg(args, AgentValue *);",
      "        if (value != NULL) {",
      "            char **grown_keys = (char **)realloc(value->keys, (value->count + 1) * sizeof(char *));",
      "            if (grown_keys != NULL) {",
      "                value->keys = grown_keys;",
      "            }",
      "            AgentValue **grown_items = (AgentValue **)realloc(value->items, (value->count + 1) * sizeof(AgentValue *));",
      "            if (grown_items != NULL) {",
      "                value->items = grown_items;",
      "            }",
      "            if (grown_keys != NULL && grown_items != NULL) {",
      "                value->keys[value->count] = __agent_debug_strdup(key);",
      "                value->items[value->count] = child;",
      "                value->count += 1;",
      "            } else {",
      "                __agent_debug_free(child);",
      "            }",
      "        } else {",
      "            __agent_debug_free(child);",
      "        }",
      "        key = va_arg(args, const char *);",
      "    }",
      "    va_end(args);",
      "    return value;",
      "}",
      "",
      "static char *__agent_debug_split_acronym(const char *input) {",
      "    size_t n = strlen(input);",
      "    char *result = (char *)malloc(n * 2 + 1);",
      "    if (result == NULL) {",
      "        return NULL;",
      "    }",
      "    size_t out = 0;",
      "    size_t i = 0;",
      "    while (i < n) {",
      "        unsigned char ci = (unsigned char)input[i];",
      "        if (ci >= 'A' && ci <= 'Z') {",
      "            size_t j = i;",
      "            while (j < n) {",
      "                unsigned char cj = (unsigned char)input[j];",
      "                if (cj >= 'A' && cj <= 'Z') {",
      "                    j += 1;",
      "                } else {",
      "                    break;",
      "                }",
      "            }",
      "            unsigned char after = (j < n) ? (unsigned char)input[j] : 0;",
      "            if (j - i >= 2 && j < n && after >= 'a' && after <= 'z') {",
      "                for (size_t k = i; k < j - 1; k += 1) {",
      "                    result[out] = input[k];",
      "                    out += 1;",
      "                }",
      "                result[out] = '_';",
      "                out += 1;",
      "                result[out] = input[j - 1];",
      "                out += 1;",
      "                result[out] = input[j];",
      "                out += 1;",
      "                i = j + 1;",
      "                continue;",
      "            }",
      "            for (size_t k = i; k < j; k += 1) {",
      "                result[out] = input[k];",
      "                out += 1;",
      "            }",
      "            i = j;",
      "            continue;",
      "        }",
      "        result[out] = input[i];",
      "        out += 1;",
      "        i += 1;",
      "    }",
      "    result[out] = 0;",
      "    return result;",
      "}",
      "",
      "static char *__agent_debug_split_camel(const char *input) {",
      "    size_t n = strlen(input);",
      "    char *result = (char *)malloc(n * 2 + 1);",
      "    if (result == NULL) {",
      "        return NULL;",
      "    }",
      "    size_t out = 0;",
      "    for (size_t i = 0; i < n; i += 1) {",
      "        unsigned char ci = (unsigned char)input[i];",
      "        result[out] = input[i];",
      "        out += 1;",
      "        int boundary = (ci >= 'a' && ci <= 'z') || (ci >= '0' && ci <= '9');",
      "        if (boundary && i + 1 < n) {",
      "            unsigned char next = (unsigned char)input[i + 1];",
      "            if (next >= 'A' && next <= 'Z') {",
      "                result[out] = '_';",
      "                out += 1;",
      "            }",
      "        }",
      "    }",
      "    result[out] = 0;",
      "    return result;",
      "}",
      "",
      "static char *__agent_debug_normalize_key(const char *key) {",
      "    char *acronym = __agent_debug_split_acronym(key);",
      "    if (acronym == NULL) {",
      "        return NULL;",
      "    }",
      "    char *split = __agent_debug_split_camel(acronym);",
      "    free(acronym);",
      "    if (split == NULL) {",
      "        return NULL;",
      "    }",
      "    size_t n = strlen(split);",
      "    char *normalized = (char *)malloc(n + 1);",
      "    if (normalized == NULL) {",
      "        free(split);",
      "        return NULL;",
      "    }",
      "    size_t out = 0;",
      "    int pending_underscore = 0;",
      "    for (size_t i = 0; i < n; i += 1) {",
      "        unsigned char c = (unsigned char)split[i];",
      "        int alnum = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9');",
      "        if (alnum) {",
      "            if (pending_underscore && out > 0) {",
      "                normalized[out] = '_';",
      "                out += 1;",
      "            }",
      "            pending_underscore = 0;",
      "            if (c >= 'A' && c <= 'Z') {",
      "                normalized[out] = (char)(c - 'A' + 'a');",
      "                out += 1;",
      "            } else {",
      "                normalized[out] = (char)c;",
      "                out += 1;",
      "            }",
      "        } else {",
      "            pending_underscore = 1;",
      "        }",
      "    }",
      "    normalized[out] = 0;",
      "    free(split);",
      "    return normalized;",
      "}",
      "",
      "static int __agent_debug_is_secret_key(const char *key) {",
      "    char *normalized = __agent_debug_normalize_key(key);",
      "    if (normalized == NULL) {",
      "        return 0;",
      "    }",
      "    size_t norm_len = strlen(normalized);",
      "    int secret = 0;",
      "    size_t exact_count = sizeof(AGENT_DEBUG_SECRET_KEYS) / sizeof(AGENT_DEBUG_SECRET_KEYS[0]);",
      "    for (size_t i = 0; i < exact_count; i += 1) {",
      "        if (strcmp(normalized, AGENT_DEBUG_SECRET_KEYS[i]) == 0) {",
      "            secret = 1;",
      "            break;",
      "        }",
      "    }",
      "    if (!secret) {",
      "        size_t suffix_count = sizeof(AGENT_DEBUG_SECRET_SUFFIXES) / sizeof(AGENT_DEBUG_SECRET_SUFFIXES[0]);",
      "        for (size_t i = 0; i < suffix_count; i += 1) {",
      "            const char *suffix = AGENT_DEBUG_SECRET_SUFFIXES[i];",
      "            size_t suffix_len = strlen(suffix);",
      "            if (norm_len >= suffix_len && strcmp(normalized + (norm_len - suffix_len), suffix) == 0) {",
      "                size_t boundary = norm_len - suffix_len;",
      "                if (boundary == 0 || normalized[boundary - 1] == '_') {",
      "                    secret = 1;",
      "                    break;",
      "                }",
      "            }",
      "        }",
      "    }",
      "    free(normalized);",
      "    return secret;",
      "}",
      "",
      "static void __agent_debug_append(AgentDebugBuffer *buf, const char *text, size_t n) {",
      "    if (buf->overflow) {",
      "        return;",
      "    }",
      "    if (n > buf->capacity - buf->length) {",
      "        buf->overflow = 1;",
      "        return;",
      "    }",
      "    for (size_t i = 0; i < n; i += 1) {",
      "        buf->buffer[buf->length + i] = text[i];",
      "    }",
      "    buf->length += n;",
      "}",
      "",
      "static void __agent_debug_append_char(AgentDebugBuffer *buf, char c) {",
      "    __agent_debug_append(buf, &c, 1);",
      "}",
      "",
      "static void __agent_debug_append_ll(AgentDebugBuffer *buf, long long number) {",
      "    char temp[32];",
      '    int written = snprintf(temp, sizeof(temp), "%lld", number);',
      "    if (written < 0) {",
      "        buf->overflow = 1;",
      "        return;",
      "    }",
      "    __agent_debug_append(buf, temp, (size_t)written);",
      "}",
      "",
      "static void __agent_debug_append_double(AgentDebugBuffer *buf, double number) {",
      "    char temp[64];",
      '    int written = snprintf(temp, sizeof(temp), "%.17g", number);',
      "    if (written < 0) {",
      "        buf->overflow = 1;",
      "        return;",
      "    }",
      "    __agent_debug_append(buf, temp, (size_t)written);",
      "}",
      "",
      "static void __agent_debug_write_string(AgentDebugBuffer *buf, const char *text) {",
      "    char backslash = (char)0x5C;",
      "    char quote = (char)0x22;",
      "    __agent_debug_append_char(buf, quote);",
      "    if (text != NULL) {",
      "        for (const unsigned char *p = (const unsigned char *)text; *p != 0; p += 1) {",
      "            unsigned int code = (unsigned int)(*p);",
      "            char c = (char)(*p);",
      "            if (c == quote) {",
      "                __agent_debug_append_char(buf, backslash);",
      "                __agent_debug_append_char(buf, quote);",
      "            } else if (c == backslash) {",
      "                __agent_debug_append_char(buf, backslash);",
      "                __agent_debug_append_char(buf, backslash);",
      "            } else if (code == 8) {",
      "                __agent_debug_append_char(buf, backslash);",
      "                __agent_debug_append_char(buf, 'b');",
      "            } else if (code == 9) {",
      "                __agent_debug_append_char(buf, backslash);",
      "                __agent_debug_append_char(buf, 't');",
      "            } else if (code == 10) {",
      "                __agent_debug_append_char(buf, backslash);",
      "                __agent_debug_append_char(buf, 'n');",
      "            } else if (code == 12) {",
      "                __agent_debug_append_char(buf, backslash);",
      "                __agent_debug_append_char(buf, 'f');",
      "            } else if (code == 13) {",
      "                __agent_debug_append_char(buf, backslash);",
      "                __agent_debug_append_char(buf, 'r');",
      "            } else if (code < 32) {",
      '                const char *digits = "0123456789abcdef";',
      "                __agent_debug_append_char(buf, backslash);",
      "                __agent_debug_append_char(buf, 'u');",
      "                __agent_debug_append_char(buf, '0');",
      "                __agent_debug_append_char(buf, '0');",
      "                __agent_debug_append_char(buf, digits[(code >> 4) & 15]);",
      "                __agent_debug_append_char(buf, digits[code & 15]);",
      "            } else {",
      "                __agent_debug_append_char(buf, c);",
      "            }",
      "        }",
      "    }",
      "    __agent_debug_append_char(buf, quote);",
      "}",
      "",
      "static int __agent_debug_write_value(AgentDebugBuffer *buf, const AgentValue *value, int depth) {",
      "    if (depth > 64) {",
      "        return 0;",
      "    }",
      "    if (value == NULL) {",
      "        return 0;",
      "    }",
      "    switch (value->kind) {",
      "        case AGENT_KIND_NULL:",
      '            __agent_debug_append(buf, "null", 4);',
      "            break;",
      "        case AGENT_KIND_BOOL:",
      "            if (value->boolValue) {",
      '                __agent_debug_append(buf, "true", 4);',
      "            } else {",
      '                __agent_debug_append(buf, "false", 5);',
      "            }",
      "            break;",
      "        case AGENT_KIND_INT:",
      "            __agent_debug_append_ll(buf, value->intValue);",
      "            break;",
      "        case AGENT_KIND_DOUBLE:",
      "            if (!isfinite(value->doubleValue)) {",
      "                return 0;",
      "            }",
      "            __agent_debug_append_double(buf, value->doubleValue);",
      "            break;",
      "        case AGENT_KIND_STR:",
      "            __agent_debug_write_string(buf, value->strValue);",
      "            break;",
      "        case AGENT_KIND_ARRAY: {",
      "            __agent_debug_append_char(buf, '[');",
      "            for (size_t i = 0; i < value->count; i += 1) {",
      "                if (i > 0) {",
      "                    __agent_debug_append_char(buf, ',');",
      "                }",
      "                if (!__agent_debug_write_value(buf, value->items[i], depth + 1)) {",
      "                    return 0;",
      "                }",
      "            }",
      "            __agent_debug_append_char(buf, ']');",
      "            break;",
      "        }",
      "        case AGENT_KIND_OBJECT: {",
      "            __agent_debug_append_char(buf, '{');",
      "            for (size_t i = 0; i < value->count; i += 1) {",
      "                if (i > 0) {",
      "                    __agent_debug_append_char(buf, ',');",
      "                }",
      "                __agent_debug_write_string(buf, value->keys[i]);",
      "                __agent_debug_append_char(buf, ':');",
      "                if (__agent_debug_is_secret_key(value->keys[i])) {",
      '                    __agent_debug_write_string(buf, "[REDACTED]");',
      "                } else if (!__agent_debug_write_value(buf, value->items[i], depth + 1)) {",
      "                    return 0;",
      "                }",
      "            }",
      "            __agent_debug_append_char(buf, '}');",
      "            break;",
      "        }",
      "    }",
      "    return 1;",
      "}",
      "",
      "static long long __agent_debug_timestamp_ms(void) {",
      "#ifdef _WIN32",
      "    return (long long)time(NULL) * 1000;",
      "#else",
      "    struct timespec ts;",
      "    if (clock_gettime(CLOCK_REALTIME, &ts) != 0) {",
      "        return 0;",
      "    }",
      "    return (long long)ts.tv_sec * 1000 + (long long)ts.tv_nsec / 1000000;",
      "#endif",
      "}",
      "",
      "static void __agentDebugEmit(const char *hypothesisId, const char *location,",
      "                             const char *message, AgentValue *data) {",
      "    char storage[65536 + 4096];",
      "    AgentDebugBuffer buf;",
      "    buf.buffer = storage;",
      "    buf.length = 0;",
      "    buf.capacity = sizeof(storage);",
      "    buf.overflow = 0;",
      "    int serialized = 1;",
      "    __agent_debug_append_char(&buf, '{');",
      '    __agent_debug_write_string(&buf, "hypothesisId");',
      "    __agent_debug_append_char(&buf, ':');",
      "    __agent_debug_write_string(&buf, hypothesisId);",
      "    __agent_debug_append_char(&buf, ',');",
      '    __agent_debug_write_string(&buf, "location");',
      "    __agent_debug_append_char(&buf, ':');",
      "    __agent_debug_write_string(&buf, location);",
      "    __agent_debug_append_char(&buf, ',');",
      '    __agent_debug_write_string(&buf, "message");',
      "    __agent_debug_append_char(&buf, ':');",
      "    __agent_debug_write_string(&buf, message);",
      "    __agent_debug_append_char(&buf, ',');",
      '    __agent_debug_write_string(&buf, "data");',
      "    __agent_debug_append_char(&buf, ':');",
      "    if (!__agent_debug_write_value(&buf, data, 0)) {",
      "        serialized = 0;",
      "    }",
      "    if (serialized) {",
      "        __agent_debug_append_char(&buf, ',');",
      '        __agent_debug_write_string(&buf, "timestamp");',
      "        __agent_debug_append_char(&buf, ':');",
      "        __agent_debug_append_ll(&buf, __agent_debug_timestamp_ms());",
      "        __agent_debug_append_char(&buf, '}');",
      "        __agent_debug_append_char(&buf, (char)0x0A);",
      "    }",
      "    if (serialized && !buf.overflow && buf.length <= 65536) {",
      "#ifdef _WIN32",
      '        FILE *file = fopen("__APPEND_PATH__", "ab");',
      "        if (file != NULL) {",
      "            size_t wrote = fwrite(storage, 1, buf.length, file);",
      "            (void)wrote;",
      "            fclose(file);",
      "        }",
      "#else",
      '        int fd = open("__APPEND_PATH__", O_WRONLY | O_APPEND | O_CREAT, 0600);',
      "        if (fd >= 0) {",
      "            ssize_t wrote = write(fd, storage, buf.length);",
      "            (void)wrote;",
      "            close(fd);",
      "        }",
      "#endif",
      "    }",
      "    __agent_debug_free(data);",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "c",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible C AgentValue that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
