import type { ProbeTemplates } from "./render";

export function renderCppTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      '__agentDebugEmit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "#include <chrono>",
      "#include <cmath>",
      "#include <fstream>",
      "#include <initializer_list>",
      "#include <iomanip>",
      "#include <iostream>",
      "#include <sstream>",
      "#include <string>",
      "#include <utility>",
      "#include <vector>",
      "#ifndef _WIN32",
      "#include <sys/stat.h>",
      "#endif",
      "",
      "enum class AgentKind { Null, Bool, Int, Double, Str, Array, Object };",
      "",
      "struct AgentValue {",
      "    AgentKind kind = AgentKind::Null;",
      "    bool boolValue = false;",
      "    long long intValue = 0;",
      "    double doubleValue = 0.0;",
      "    std::string strValue;",
      "    std::vector<AgentValue> arrayValue;",
      "    std::vector<std::pair<std::string, AgentValue>> objectValue;",
      "",
      "    AgentValue() {}",
      "    AgentValue(bool v) { kind = AgentKind::Bool; boolValue = v; }",
      "    AgentValue(long long v) { kind = AgentKind::Int; intValue = v; }",
      "    AgentValue(double v) { kind = AgentKind::Double; doubleValue = v; }",
      "    AgentValue(const char* v) { kind = AgentKind::Str; strValue = v; }",
      "    AgentValue(const std::string& v) { kind = AgentKind::Str; strValue = v; }",
      "    AgentValue(std::initializer_list<AgentValue> items) {",
      "        bool isObject = items.size() > 0;",
      "        for (const auto& item : items) {",
      "            if (item.kind != AgentKind::Array || item.arrayValue.size() != 2 ||",
      "                item.arrayValue[0].kind != AgentKind::Str) {",
      "                isObject = false;",
      "                break;",
      "            }",
      "        }",
      "        if (isObject) {",
      "            kind = AgentKind::Object;",
      "            for (const auto& item : items) {",
      "                objectValue.emplace_back(item.arrayValue[0].strValue, item.arrayValue[1]);",
      "            }",
      "        } else {",
      "            kind = AgentKind::Array;",
      "            arrayValue = std::vector<AgentValue>(items);",
      "        }",
      "    }",
      "};",
      "",
      "static const char* const AGENT_DEBUG_SECRET_KEYS[] = {",
      '    "authorization", "authorization_header", "cookie", "set_cookie",',
      '    "password", "passwd", "pwd", "private_key", "secret", "token",',
      '    "credential", "credentials"};',
      "",
      "static const char* const AGENT_DEBUG_SECRET_SUFFIXES[] = {",
      '    "api_key", "api_token", "oauth_token", "o_auth_token", "private_key",',
      '    "client_secret", "access_token", "refresh_token", "id_token",',
      '    "auth_token", "bearer_token"};',
      "",
      "static std::string __agent_debug_split_acronym(const std::string& input) {",
      "    std::string result;",
      "    size_t n = input.size();",
      "    size_t i = 0;",
      "    while (i < n) {",
      "        unsigned char ci = static_cast<unsigned char>(input[i]);",
      "        if (ci >= 'A' && ci <= 'Z') {",
      "            size_t j = i;",
      "            while (j < n) {",
      "                unsigned char cj = static_cast<unsigned char>(input[j]);",
      "                if (cj >= 'A' && cj <= 'Z') {",
      "                    j += 1;",
      "                } else {",
      "                    break;",
      "                }",
      "            }",
      "            unsigned char after = (j < n) ? static_cast<unsigned char>(input[j]) : 0;",
      "            if (j - i >= 2 && j < n && after >= 'a' && after <= 'z') {",
      "                for (size_t k = i; k < j - 1; k += 1) {",
      "                    result.push_back(input[k]);",
      "                }",
      "                result.push_back('_');",
      "                result.push_back(input[j - 1]);",
      "                result.push_back(input[j]);",
      "                i = j + 1;",
      "                continue;",
      "            }",
      "            for (size_t k = i; k < j; k += 1) {",
      "                result.push_back(input[k]);",
      "            }",
      "            i = j;",
      "            continue;",
      "        }",
      "        result.push_back(input[i]);",
      "        i += 1;",
      "    }",
      "    return result;",
      "}",
      "",
      "static std::string __agent_debug_split_camel(const std::string& input) {",
      "    std::string result;",
      "    size_t n = input.size();",
      "    for (size_t i = 0; i < n; i += 1) {",
      "        unsigned char ci = static_cast<unsigned char>(input[i]);",
      "        result.push_back(input[i]);",
      "        bool boundary = (ci >= 'a' && ci <= 'z') || (ci >= '0' && ci <= '9');",
      "        if (boundary && i + 1 < n) {",
      "            unsigned char next = static_cast<unsigned char>(input[i + 1]);",
      "            if (next >= 'A' && next <= 'Z') {",
      "                result.push_back('_');",
      "            }",
      "        }",
      "    }",
      "    return result;",
      "}",
      "",
      "static std::string __agent_debug_normalize_key(const std::string& key) {",
      "    std::string split = __agent_debug_split_camel(__agent_debug_split_acronym(key));",
      "    std::string normalized;",
      "    bool pending_underscore = false;",
      "    for (unsigned char c : split) {",
      "        bool alnum = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9');",
      "        if (alnum) {",
      "            if (pending_underscore && !normalized.empty()) {",
      "                normalized.push_back('_');",
      "            }",
      "            pending_underscore = false;",
      "            if (c >= 'A' && c <= 'Z') {",
      "                normalized.push_back(static_cast<char>(c - 'A' + 'a'));",
      "            } else {",
      "                normalized.push_back(static_cast<char>(c));",
      "            }",
      "        } else {",
      "            pending_underscore = true;",
      "        }",
      "    }",
      "    return normalized;",
      "}",
      "",
      "static bool __agent_debug_is_secret_key(const std::string& key) {",
      "    std::string normalized = __agent_debug_normalize_key(key);",
      "    for (const auto& exact : AGENT_DEBUG_SECRET_KEYS) {",
      "        if (normalized == exact) {",
      "            return true;",
      "        }",
      "    }",
      "    for (const auto& suffix : AGENT_DEBUG_SECRET_SUFFIXES) {",
      "        std::string tail(suffix);",
      "        if (normalized.size() >= tail.size() &&",
      "            normalized.compare(normalized.size() - tail.size(), tail.size(), tail) == 0) {",
      "            size_t boundary = normalized.size() - tail.size();",
      "            if (boundary == 0 || normalized[boundary - 1] == '_') {",
      "                return true;",
      "            }",
      "        }",
      "    }",
      "    return false;",
      "}",
      "",
      "static void __agent_debug_write_string(std::ostringstream& out, const std::string& text) {",
      "    const char backslash = static_cast<char>(0x5C);",
      "    const char quote = static_cast<char>(0x22);",
      "    out << quote;",
      "    for (unsigned char c : text) {",
      "        unsigned int code = static_cast<unsigned int>(c);",
      "        if (c == quote) {",
      "            out << backslash << quote;",
      "        } else if (c == backslash) {",
      "            out << backslash << backslash;",
      "        } else if (code == 8) {",
      "            out << backslash << 'b';",
      "        } else if (code == 9) {",
      "            out << backslash << 't';",
      "        } else if (code == 10) {",
      "            out << backslash << 'n';",
      "        } else if (code == 12) {",
      "            out << backslash << 'f';",
      "        } else if (code == 13) {",
      "            out << backslash << 'r';",
      "        } else if (code < 32) {",
      '            const char* digits = "0123456789abcdef";',
      "            out << backslash << 'u' << '0' << '0';",
      "            out << digits[(code >> 4) & 15] << digits[code & 15];",
      "        } else {",
      "            out << static_cast<char>(c);",
      "        }",
      "    }",
      "    out << quote;",
      "}",
      "",
      "static bool __agent_debug_write_value(std::ostringstream& out, const AgentValue& value, int depth) {",
      "    if (depth > 64) {",
      "        return false;",
      "    }",
      "    switch (value.kind) {",
      "        case AgentKind::Null:",
      '            out << "null";',
      "            break;",
      "        case AgentKind::Bool:",
      '            out << (value.boolValue ? "true" : "false");',
      "            break;",
      "        case AgentKind::Int:",
      "            out << value.intValue;",
      "            break;",
      "        case AgentKind::Double: {",
      "            if (!std::isfinite(value.doubleValue)) {",
      "                return false;",
      "            }",
      "            std::ostringstream number;",
      "            number << std::setprecision(17) << value.doubleValue;",
      "            out << number.str();",
      "            break;",
      "        }",
      "        case AgentKind::Str:",
      "            __agent_debug_write_string(out, value.strValue);",
      "            break;",
      "        case AgentKind::Array: {",
      "            out << '[';",
      "            int index = 0;",
      "            for (const auto& item : value.arrayValue) {",
      "                if (index > 0) {",
      "                    out << ',';",
      "                }",
      "                index += 1;",
      "                if (!__agent_debug_write_value(out, item, depth + 1)) {",
      "                    return false;",
      "                }",
      "            }",
      "            out << ']';",
      "            break;",
      "        }",
      "        case AgentKind::Object: {",
      "            out << '{';",
      "            int index = 0;",
      "            for (const auto& entry : value.objectValue) {",
      "                if (index > 0) {",
      "                    out << ',';",
      "                }",
      "                index += 1;",
      "                __agent_debug_write_string(out, entry.first);",
      "                out << ':';",
      "                if (__agent_debug_is_secret_key(entry.first)) {",
      '                    __agent_debug_write_string(out, "[REDACTED]");',
      "                } else if (!__agent_debug_write_value(out, entry.second, depth + 1)) {",
      "                    return false;",
      "                }",
      "            }",
      "            out << '}';",
      "            break;",
      "        }",
      "    }",
      "    return true;",
      "}",
      "",
      "static long long __agent_debug_timestamp_ms() {",
      "    return std::chrono::duration_cast<std::chrono::milliseconds>(",
      "               std::chrono::system_clock::now().time_since_epoch())",
      "        .count();",
      "}",
      "",
      "static void __agentDebugEmit(const std::string& hypothesisId, const std::string& location,",
      "                             const std::string& message, const AgentValue& data) {",
      "    try {",
      "        std::ostringstream out;",
      "        out << '{';",
      '        __agent_debug_write_string(out, "hypothesisId");',
      "        out << ':';",
      "        __agent_debug_write_string(out, hypothesisId);",
      "        out << ',';",
      '        __agent_debug_write_string(out, "location");',
      "        out << ':';",
      "        __agent_debug_write_string(out, location);",
      "        out << ',';",
      '        __agent_debug_write_string(out, "message");',
      "        out << ':';",
      "        __agent_debug_write_string(out, message);",
      "        out << ',';",
      '        __agent_debug_write_string(out, "data");',
      "        out << ':';",
      "        if (!__agent_debug_write_value(out, data, 0)) {",
      "            return;",
      "        }",
      "        out << ',';",
      '        __agent_debug_write_string(out, "timestamp");',
      "        out << ':';",
      "        out << __agent_debug_timestamp_ms();",
      "        out << '}';",
      "        out << static_cast<char>(0x0A);",
      "        std::string payload = out.str();",
      "        if (payload.size() > 65536) {",
      "            return;",
      "        }",
      '        std::ofstream file("__APPEND_PATH__", std::ios::out | std::ios::app | std::ios::binary);',
      "        if (!file.is_open()) {",
      "            return;",
      "        }",
      "        file << payload;",
      "        file.close();",
      "#ifndef _WIN32",
      '        chmod("__APPEND_PATH__", 0600);',
      "#endif",
      "    } catch (...) {",
      "        return;",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "cpp",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible C++ AgentValue that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
