import type { ProbeTemplates } from "./render";

export function renderCppTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      'agent_debug_mode::emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_JSON_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    dataEncoding: "serialized-json",
    helperTemplate: [
      "// #region agent log",
      "#include <chrono>",
      "#include <string>",
      "#ifdef _WIN32",
      "#include <fstream>",
      "#include <ios>",
      "#else",
      "#include <fcntl.h>",
      "#include <unistd.h>",
      "#endif",
      "",
      "#define AGENT_DEBUG_STRINGIFY_IMPL(value) #value",
      "#define AGENT_DEBUG_STRINGIFY(value) AGENT_DEBUG_STRINGIFY_IMPL(value)",
      "",
      "namespace agent_debug_mode {",
      "",
      "inline std::string json_string(const std::string& text) {",
      "    const char backslash = static_cast<char>(0x5C);",
      "    const char quote = static_cast<char>(0x22);",
      "    std::string out;",
      "    out.push_back(quote);",
      "    for (unsigned char c : text) {",
      "        unsigned int code = static_cast<unsigned int>(c);",
      "        if (c == quote) {",
      "            out.push_back(backslash);",
      "            out.push_back(quote);",
      "        } else if (c == backslash) {",
      "            out.push_back(backslash);",
      "            out.push_back(backslash);",
      "        } else if (code == 8) {",
      "            out.push_back(backslash);",
      "            out.push_back('b');",
      "        } else if (code == 9) {",
      "            out.push_back(backslash);",
      "            out.push_back('t');",
      "        } else if (code == 10) {",
      "            out.push_back(backslash);",
      "            out.push_back('n');",
      "        } else if (code == 12) {",
      "            out.push_back(backslash);",
      "            out.push_back('f');",
      "        } else if (code == 13) {",
      "            out.push_back(backslash);",
      "            out.push_back('r');",
      "        } else if (code < 32) {",
      '            const char* digits = "0123456789abcdef";',
      "            out.push_back(backslash);",
      "            out.push_back('u');",
      "            out.push_back('0');",
      "            out.push_back('0');",
      "            out.push_back(digits[(code >> 4) & 15]);",
      "            out.push_back(digits[code & 15]);",
      "        } else {",
      "            out.push_back(static_cast<char>(c));",
      "        }",
      "    }",
      "    out.push_back(quote);",
      "    return out;",
      "}",
      "",
      "inline long long timestamp_ms() {",
      "    return std::chrono::duration_cast<std::chrono::milliseconds>(",
      "               std::chrono::system_clock::now().time_since_epoch())",
      "        .count();",
      "}",
      "",
      "inline void emit(const std::string& hypothesis_id, const std::string& location,",
      "                 const std::string& message, const std::string& data_json) {",
      "    try {",
      "        if (data_json.empty()) {",
      "            return;",
      "        }",
      "        std::string out;",
      "        out.push_back('{');",
      '        out += json_string("hypothesisId");',
      "        out.push_back(':');",
      "        out += json_string(hypothesis_id);",
      "        out.push_back(',');",
      '        out += json_string("location");',
      "        out.push_back(':');",
      "        out += json_string(location);",
      "        out.push_back(',');",
      '        out += json_string("message");',
      "        out.push_back(':');",
      "        out += json_string(message);",
      "        out.push_back(',');",
      '        out += json_string("data");',
      "        out.push_back(':');",
      "        out += data_json;",
      "        out.push_back(',');",
      '        out += json_string("timestamp");',
      "        out.push_back(':');",
      "        out += std::to_string(timestamp_ms());",
      "        out.push_back('}');",
      "        out.push_back(static_cast<char>(0x0A));",
      "        if (out.size() > 65536) {",
      "            return;",
      "        }",
      "#ifdef _WIN32",
      '        std::ofstream file("__APPEND_PATH__", std::ios::out | std::ios::app | std::ios::binary);',
      "        if (!file.is_open()) {",
      "            return;",
      "        }",
      "        file << out;",
      "#else",
      '        int fd = open("__APPEND_PATH__", O_WRONLY | O_APPEND | O_CREAT, 0600);',
      "        if (fd >= 0) {",
      "            ssize_t wrote = write(fd, out.data(), out.size());",
      "            (void)wrote;",
      "            close(fd);",
      "        }",
      "#endif",
      "    } catch (...) {",
      "        return;",
      "    }",
      "}",
      "",
      "}  // namespace agent_debug_mode",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "cpp",
    placement: { call: "statement", helper: "file-start" },
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_JSON_EXPRESSION__:
        "Replace with an expression that returns one complete valid JSON value containing no secrets. Use the application's serializer when available; otherwise pass agent_debug_mode::json_string(text).",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
