import type { ProbeTemplates } from "./render";

export function renderCSharpTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      'AgentDebugLog.Emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "using System;",
      "using System.IO;",
      "using System.Text;",
      "using System.Text.Json;",
      "",
      "internal static class AgentDebugLog",
      "{",
      "    internal static void Emit(string hypothesisId, string location, string message, object? data)",
      "    {",
      "        try",
      "        {",
      "            var json = JsonSerializer.Serialize(new",
      "            {",
      "                hypothesisId,",
      "                location,",
      "                message,",
      "                data,",
      "                timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),",
      '            }) + "\\n";',
      "            var payload = new UTF8Encoding(false).GetBytes(json);",
      "            if (payload.Length > 65_536) return;",
      '            using var stream = new FileStream("__APPEND_PATH__", FileMode.Append, FileAccess.Write, FileShare.ReadWrite);',
      "            stream.Write(payload, 0, payload.Length);",
      "        }",
      "        catch",
      "        {",
      "            // Observations must never change application behavior.",
      "        }",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "csharp",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible C# expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
