import type { ProbeTemplates } from "./render";

export function renderCSharpTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      'AgentDebugLog.Emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "using System;",
      "using System.Collections;",
      "using System.Collections.Generic;",
      "using System.IO;",
      "using System.Text;",
      "using System.Text.Json;",
      "using System.Text.RegularExpressions;",
      "",
      "internal static class AgentDebugLog",
      "{",
      "    private static readonly HashSet<string> SecretKeys = new(StringComparer.Ordinal)",
      "    {",
      '        "authorization", "authorization_header", "cookie", "set_cookie",',
      '        "password", "passwd", "pwd", "private_key", "secret", "token",',
      '        "credential", "credentials",',
      "    };",
      "",
      "    private static bool IsSecretKey(string key)",
      "    {",
      '        var normalized = Regex.Replace(key, "([A-Z]+)([A-Z][a-z])", "$1_$2");',
      '        normalized = Regex.Replace(normalized, "([a-z0-9])([A-Z])", "$1_$2");',
      '        normalized = Regex.Replace(normalized, "[^a-zA-Z0-9]+", "_").ToLowerInvariant().Trim(\'_\');',
      "        return SecretKeys.Contains(normalized) || Regex.IsMatch(",
      "            normalized,",
      '            "(^|_)(password|passwd|pwd|secret|token|api_key|api_token|oauth_token|o_auth_token|authorization|authorization_header|cookie|set_cookie|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token|credential|credentials)$");',
      "    }",
      "",
      "    private static object? Redact(object? value)",
      "    {",
      "        return Redact(value, new HashSet<object>(ReferenceEqualityComparer.Instance), 0);",
      "    }",
      "",
      "    private static object? Redact(object? value, HashSet<object> active, int depth)",
      "    {",
      '        if (depth > 64) throw new InvalidOperationException("Observation graph is too deep");',
      "        if (value is null || value is string || value.GetType().IsValueType)",
      "            return value;",
      '        if (!active.Add(value)) throw new InvalidOperationException("Cyclic observation graph");',
      "        try",
      "        {",
      "            if (value is IDictionary dictionary)",
      "            {",
      "                var redacted = new Dictionary<string, object?>();",
      "                foreach (DictionaryEntry entry in dictionary)",
      "                {",
      "                    var key = Convert.ToString(entry.Key) ?? string.Empty;",
      '                    redacted[key] = IsSecretKey(key) ? "[REDACTED]" : Redact(entry.Value, active, depth + 1);',
      "                }",
      "                return redacted;",
      "            }",
      "            if (value is IEnumerable enumerable)",
      "            {",
      "                var redacted = new List<object?>();",
      "                foreach (var item in enumerable) redacted.Add(Redact(item, active, depth + 1));",
      "                return redacted;",
      "            }",
      "            var properties = new Dictionary<string, object?>();",
      "            foreach (var property in value.GetType().GetProperties())",
      "            {",
      "                if (!property.CanRead || property.GetIndexParameters().Length != 0) continue;",
      "                properties[property.Name] = IsSecretKey(property.Name)",
      '                    ? "[REDACTED]"',
      "                    : Redact(property.GetValue(value), active, depth + 1);",
      "            }",
      "            return properties;",
      "        }",
      "        finally",
      "        {",
      "            active.Remove(value);",
      "        }",
      "    }",
      "",
      "    internal static void Emit(string hypothesisId, string location, string message, object? data)",
      "    {",
      "        try",
      "        {",
      "            var json = JsonSerializer.Serialize(new",
      "            {",
      "                hypothesisId,",
      "                location,",
      "                message,",
      "                data = Redact(data),",
      "                timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),",
      '            }) + "\\n";',
      "            var payload = new UTF8Encoding(false).GetBytes(json);",
      "            if (payload.Length > 65_536) return;",
      '            using var stream = new FileStream("__APPEND_PATH__", FileMode.Append, FileAccess.Write, FileShare.ReadWrite);',
      "            stream.Write(payload, 0, payload.Length);",
      "        }",
      "        catch",
      "        {",
      "            // Observations must never change application behavior.",
      "        }",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "csharp",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible C# expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
