import type { ProbeTemplates } from "./render";

export function renderGoTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      '__agentDebugEmit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__)',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      'import "encoding/json"',
      'import "os"',
      'import "reflect"',
      'import "regexp"',
      'import "strings"',
      'import "time"',
      "",
      'var __agentDebugAcronymBoundary = regexp.MustCompile("([A-Z]+)([A-Z][a-z])")',
      'var __agentDebugCamelBoundary = regexp.MustCompile("([a-z0-9])([A-Z])")',
      'var __agentDebugSeparators = regexp.MustCompile("[^a-zA-Z0-9]+")',
      'var __agentDebugSecretSuffix = regexp.MustCompile("(^|_)(api_key|api_token|oauth_token|o_auth_token|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token)$")',
      "var __agentDebugSecretKeys = map[string]bool{",
      '\t"authorization": true, "authorization_header": true, "cookie": true, "set_cookie": true,',
      '\t"password": true, "passwd": true, "pwd": true, "private_key": true, "secret": true, "token": true,',
      '\t"credential": true, "credentials": true,',
      "}",
      "",
      "func __agentDebugIsSecretKey(key string) bool {",
      '\tnormalized := __agentDebugAcronymBoundary.ReplaceAllString(key, "$' + "{1}_$" + '{2}")',
      '\tnormalized = __agentDebugCamelBoundary.ReplaceAllString(normalized, "$' +
        "{1}_$" +
        '{2}")',
      '\tnormalized = strings.Trim(__agentDebugSeparators.ReplaceAllString(strings.ToLower(normalized), "_"), "_")',
      "\treturn __agentDebugSecretKeys[normalized] || __agentDebugSecretSuffix.MatchString(normalized)",
      "}",
      "",
      "type __agentDebugVisit struct {",
      "\tkind reflect.Kind",
      "\ttypeName string",
      "\tpointer uintptr",
      "}",
      "",
      "func __agentDebugIdentity(value reflect.Value) (__agentDebugVisit, bool) {",
      "\tswitch value.Kind() {",
      "\tcase reflect.Map, reflect.Pointer, reflect.Slice:",
      "\t\tif value.IsNil() { return __agentDebugVisit{}, false }",
      "\t\treturn __agentDebugVisit{value.Kind(), value.Type().String(), value.Pointer()}, true",
      "\tdefault:",
      "\t\treturn __agentDebugVisit{}, false",
      "\t}",
      "}",
      "",
      "func __agentDebugRedact(value any) (any, bool) {",
      "\treturn __agentDebugRedactValue(reflect.ValueOf(value), make(map[__agentDebugVisit]bool), 0)",
      "}",
      "",
      "func __agentDebugRedactValue(value reflect.Value, active map[__agentDebugVisit]bool, depth int) (any, bool) {",
      "\tif depth > 64 { return nil, false }",
      "\tif !value.IsValid() { return nil, true }",
      "\tif value.Kind() == reflect.Interface {",
      "\t\tif value.IsNil() { return nil, true }",
      "\t\treturn __agentDebugRedactValue(value.Elem(), active, depth + 1)",
      "\t}",
      "\tif identity, tracked := __agentDebugIdentity(value); tracked {",
      "\t\tif active[identity] { return nil, false }",
      "\t\tactive[identity] = true",
      "\t\tdefer delete(active, identity)",
      "\t}",
      "\tif value.Kind() == reflect.Pointer {",
      "\t\treturn __agentDebugRedactValue(value.Elem(), active, depth + 1)",
      "\t}",
      "\tswitch value.Kind() {",
      "\tcase reflect.Map:",
      "\t\tredacted := make(map[string]any, value.Len())",
      "\t\titerator := value.MapRange()",
      "\t\tfor iterator.Next() {",
      "\t\t\tkey := iterator.Key()",
      "\t\t\tif key.Kind() != reflect.String { return nil, false }",
      "\t\t\tkeyText := key.String()",
      '\t\t\tif __agentDebugIsSecretKey(keyText) { redacted[keyText] = "[REDACTED]"; continue }',
      "\t\t\tchild, ok := __agentDebugRedactValue(iterator.Value(), active, depth + 1)",
      "\t\t\tif !ok { return nil, false }",
      "\t\t\tredacted[keyText] = child",
      "\t\t}",
      "\t\treturn redacted, true",
      "\tcase reflect.Array, reflect.Slice:",
      "\t\tif value.Kind() == reflect.Slice && value.IsNil() { return nil, true }",
      "\t\tredacted := make([]any, value.Len())",
      "\t\tfor index := 0; index < value.Len(); index++ {",
      "\t\t\tchild, ok := __agentDebugRedactValue(value.Index(index), active, depth + 1)",
      "\t\t\tif !ok { return nil, false }",
      "\t\t\tredacted[index] = child",
      "\t\t}",
      "\t\treturn redacted, true",
      "\tcase reflect.Struct:",
      "\t\tredacted := make(map[string]any)",
      "\t\tvalueType := value.Type()",
      "\t\tfor index := 0; index < value.NumField(); index++ {",
      "\t\t\tfieldType := valueType.Field(index)",
      '\t\t\tif fieldType.PkgPath != "" { continue }',
      "\t\t\tkey := fieldType.Name",
      '\t\t\ttag := strings.Split(fieldType.Tag.Get("json"), ",")[0]',
      '\t\t\tif tag == "-" { continue } else if tag != "" { key = tag }',
      '\t\t\tif __agentDebugIsSecretKey(key) { redacted[key] = "[REDACTED]"; continue }',
      "\t\t\tchild, ok := __agentDebugRedactValue(value.Field(index), active, depth + 1)",
      "\t\t\tif !ok { return nil, false }",
      "\t\t\tredacted[key] = child",
      "\t\t}",
      "\t\treturn redacted, true",
      "\tdefault:",
      "\t\tif value.CanInterface() { return value.Interface(), true }",
      "\t\treturn nil, false",
      "\t}",
      "}",
      "",
      "func __agentDebugEmit(hypothesisID string, location string, message string, data any) {",
      "\tdefer func() { _ = recover() }()",
      "\tredacted, ok := __agentDebugRedact(data)",
      "\tif !ok { return }",
      "\tpayload, err := json.Marshal(map[string]any{",
      '\t\t"hypothesisId": hypothesisID,',
      '\t\t"location": location,',
      '\t\t"message": message,',
      '\t\t"data": redacted,',
      '\t\t"timestamp": time.Now().UnixMilli(),',
      "\t})",
      "\tif err != nil || len(payload)+1 > 65_536 { return }",
      "\tpayload = append(payload, '\\n')",
      '\tfile, err := os.OpenFile("__APPEND_PATH__", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)',
      "\tif err != nil { return }",
      "\tdefer func() { _ = file.Close() }()",
      "\t_, _ = file.Write(payload)",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "go",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Go expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
