import type { ProbeTemplates } from "./render";

export function renderGoTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      '__agentDebugEmit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__)',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      'import "encoding/json"',
      'import "os"',
      'import "reflect"',
      'import "regexp"',
      'import "strings"',
      'import "time"',
      "",
      'var __agentDebugCamelBoundary = regexp.MustCompile("([a-z0-9])([A-Z])")',
      'var __agentDebugSeparators = regexp.MustCompile("[^a-zA-Z0-9]+")',
      'var __agentDebugSecretSuffix = regexp.MustCompile("(^|_)(password|passwd|pwd|secret|token|api_key|authorization|authorization_header|cookie|set_cookie|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token|credential|credentials)$")',
      "var __agentDebugSecretKeys = map[string]bool{",
      '\t"authorization": true, "authorization_header": true, "cookie": true, "set_cookie": true,',
      '\t"password": true, "passwd": true, "pwd": true, "private_key": true, "secret": true, "token": true,',
      '\t"credential": true, "credentials": true,',
      "}",
      "",
      "func __agentDebugIsSecretKey(key string) bool {",
      '\tnormalized := __agentDebugCamelBoundary.ReplaceAllString(key, "$' + "{1}_$" + '{2}")',
      '\tnormalized = strings.Trim(__agentDebugSeparators.ReplaceAllString(strings.ToLower(normalized), "_"), "_")',
      "\treturn __agentDebugSecretKeys[normalized] || __agentDebugSecretSuffix.MatchString(normalized)",
      "}",
      "",
      "func __agentDebugRedact(value any) any {",
      "\treturn __agentDebugRedactValue(reflect.ValueOf(value))",
      "}",
      "",
      "func __agentDebugRedactValue(value reflect.Value) any {",
      "\tif !value.IsValid() { return nil }",
      "\tfor value.Kind() == reflect.Interface || value.Kind() == reflect.Pointer {",
      "\t\tif value.IsNil() { return nil }",
      "\t\tvalue = value.Elem()",
      "\t}",
      "\tswitch value.Kind() {",
      "\tcase reflect.Map:",
      "\t\tredacted := make(map[string]any, value.Len())",
      "\t\titerator := value.MapRange()",
      "\t\tfor iterator.Next() {",
      "\t\t\tkey := iterator.Key()",
      "\t\t\tif key.Kind() != reflect.String { continue }",
      "\t\t\tkeyText := key.String()",
      '\t\t\tif __agentDebugIsSecretKey(keyText) { redacted[keyText] = "[REDACTED]" } else { redacted[keyText] = __agentDebugRedactValue(iterator.Value()) }',
      "\t\t}",
      "\t\treturn redacted",
      "\tcase reflect.Array, reflect.Slice:",
      "\t\tif value.Kind() == reflect.Slice && value.IsNil() { return nil }",
      "\t\tredacted := make([]any, value.Len())",
      "\t\tfor index := 0; index < value.Len(); index++ { redacted[index] = __agentDebugRedactValue(value.Index(index)) }",
      "\t\treturn redacted",
      "\tcase reflect.Struct:",
      "\t\tredacted := make(map[string]any)",
      "\t\tvalueType := value.Type()",
      "\t\tfor index := 0; index < value.NumField(); index++ {",
      "\t\t\tfieldType := valueType.Field(index)",
      '\t\t\tif fieldType.PkgPath != "" { continue }',
      "\t\t\tkey := fieldType.Name",
      '\t\t\ttag := strings.Split(fieldType.Tag.Get("json"), ",")[0]',
      '\t\t\tif tag == "-" { continue } else if tag != "" { key = tag }',
      '\t\t\tif __agentDebugIsSecretKey(key) { redacted[key] = "[REDACTED]" } else { redacted[key] = __agentDebugRedactValue(value.Field(index)) }',
      "\t\t}",
      "\t\treturn redacted",
      "\tdefault:",
      "\t\tif value.CanInterface() { return value.Interface() }",
      "\t\treturn nil",
      "\t}",
      "}",
      "",
      "func __agentDebugEmit(hypothesisID string, location string, message string, data any) {",
      "\tdefer func() { _ = recover() }()",
      "\tpayload, err := json.Marshal(map[string]any{",
      '\t\t"hypothesisId": hypothesisID,',
      '\t\t"location": location,',
      '\t\t"message": message,',
      '\t\t"data": __agentDebugRedact(data),',
      '\t\t"timestamp": time.Now().UnixMilli(),',
      "\t})",
      "\tif err != nil || len(payload)+1 > 65_536 { return }",
      "\tpayload = append(payload, '\\n')",
      '\tfile, err := os.OpenFile("__APPEND_PATH__", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)',
      "\tif err != nil { return }",
      "\tdefer func() { _ = file.Close() }()",
      "\t_, _ = file.Write(payload)",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "go",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Go expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
