import type { ProbeTemplates } from "./render";

export function renderJavaTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      'AgentDebugLog.Emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "class AgentDebugLog {",
      "    private static final java.util.Set<String> SECRET_KEYS = new java.util.HashSet<>(java.util.Arrays.asList(",
      '        "authorization", "authorization_header", "cookie", "set_cookie",',
      '        "password", "passwd", "pwd", "private_key", "secret", "token",',
      '        "credential", "credentials"));',
      "",
      "    private static final java.util.regex.Pattern SECRET_SUFFIX = java.util.regex.Pattern.compile(",
      '        "(^|_)(api_key|api_token|oauth_token|o_auth_token|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token)$");',
      "",
      "    private static boolean isSecretKey(String key) {",
      '        String normalized = key.replaceAll("([A-Z]+)([A-Z][a-z])", "$1_$2");',
      '        normalized = normalized.replaceAll("([a-z0-9])([A-Z])", "$1_$2");',
      '        normalized = normalized.replaceAll("[^a-zA-Z0-9]+", "_").toLowerCase(java.util.Locale.ROOT);',
      '        normalized = normalized.replaceAll("^_+", "").replaceAll("_+$", "");',
      "        return SECRET_KEYS.contains(normalized) || SECRET_SUFFIX.matcher(normalized).find();",
      "    }",
      "",
      "    private static String decapitalize(String name) {",
      "        if (name.isEmpty()) {",
      "            return name;",
      "        }",
      "        if (name.length() > 1 && Character.isUpperCase(name.charAt(0)) && Character.isUpperCase(name.charAt(1))) {",
      "            return name;",
      "        }",
      "        char[] letters = name.toCharArray();",
      "        letters[0] = Character.toLowerCase(letters[0]);",
      "        return new String(letters);",
      "    }",
      "",
      "    private static Object redact(Object value, java.util.IdentityHashMap<Object, Boolean> active, int depth) {",
      "        if (depth > 64) {",
      '            throw new IllegalStateException("Observation graph is too deep");',
      "        }",
      "        if (value == null) {",
      "            return null;",
      "        }",
      "        if (value instanceof CharSequence || value instanceof Character) {",
      "            return value.toString();",
      "        }",
      "        if (value instanceof Number || value instanceof Boolean) {",
      "            return value;",
      "        }",
      "        if (value instanceof Enum) {",
      "            return ((Enum<?>) value).name();",
      "        }",
      "        if (active.put(value, Boolean.TRUE) != null) {",
      '            throw new IllegalStateException("Cyclic observation graph");',
      "        }",
      "        try {",
      "            if (value instanceof java.util.Map) {",
      "                java.util.LinkedHashMap<String, Object> redacted = new java.util.LinkedHashMap<>();",
      "                for (java.util.Map.Entry<?, ?> entry : ((java.util.Map<?, ?>) value).entrySet()) {",
      "                    String key = String.valueOf(entry.getKey());",
      '                    redacted.put(key, isSecretKey(key) ? "[REDACTED]" : redact(entry.getValue(), active, depth + 1));',
      "                }",
      "                return redacted;",
      "            }",
      "            if (value instanceof Iterable) {",
      "                java.util.ArrayList<Object> redacted = new java.util.ArrayList<>();",
      "                for (Object item : (Iterable<?>) value) {",
      "                    redacted.add(redact(item, active, depth + 1));",
      "                }",
      "                return redacted;",
      "            }",
      "            if (value.getClass().isArray()) {",
      "                java.util.ArrayList<Object> redacted = new java.util.ArrayList<>();",
      "                int length = java.lang.reflect.Array.getLength(value);",
      "                for (int index = 0; index < length; index += 1) {",
      "                    redacted.add(redact(java.lang.reflect.Array.get(value, index), active, depth + 1));",
      "                }",
      "                return redacted;",
      "            }",
      "            java.util.LinkedHashMap<String, Object> members = new java.util.LinkedHashMap<>();",
      "            Class<?> type = value.getClass();",
      "            for (java.lang.reflect.Method method : type.getMethods()) {",
      "                if (method.getParameterCount() != 0 || method.getReturnType() == void.class) {",
      "                    continue;",
      "                }",
      "                if (java.lang.reflect.Modifier.isStatic(method.getModifiers()) || method.getDeclaringClass() == Object.class) {",
      "                    continue;",
      "                }",
      "                String name = method.getName();",
      "                String property;",
      '                if (name.startsWith("get") && name.length() > 3) {',
      "                    property = decapitalize(name.substring(3));",
      '                } else if (name.startsWith("is") && name.length() > 2 && (method.getReturnType() == boolean.class || method.getReturnType() == Boolean.class)) {',
      "                    property = decapitalize(name.substring(2));",
      "                } else {",
      "                    continue;",
      "                }",
      "                Object raw;",
      "                try {",
      "                    method.setAccessible(true);",
      "                    raw = method.invoke(value);",
      "                } catch (Throwable failure) {",
      "                    continue;",
      "                }",
      '                members.put(property, isSecretKey(property) ? "[REDACTED]" : redact(raw, active, depth + 1));',
      "            }",
      "            for (java.lang.reflect.Field field : type.getFields()) {",
      "                if (java.lang.reflect.Modifier.isStatic(field.getModifiers())) {",
      "                    continue;",
      "                }",
      "                Object raw;",
      "                try {",
      "                    field.setAccessible(true);",
      "                    raw = field.get(value);",
      "                } catch (Throwable failure) {",
      "                    continue;",
      "                }",
      '                members.put(field.getName(), isSecretKey(field.getName()) ? "[REDACTED]" : redact(raw, active, depth + 1));',
      "            }",
      "            return members;",
      "        } finally {",
      "            active.remove(value);",
      "        }",
      "    }",
      "",
      "    private static void writeString(StringBuilder out, String text) {",
      "        char backslash = (char) 92;",
      "        char quote = (char) 34;",
      "        out.append(quote);",
      "        for (int index = 0; index < text.length(); index += 1) {",
      "            char symbol = text.charAt(index);",
      "            if (symbol == quote) {",
      "                out.append(backslash).append(quote);",
      "            } else if (symbol == backslash) {",
      "                out.append(backslash).append(backslash);",
      "            } else if (symbol == (char) 8) {",
      "                out.append(backslash).append('b');",
      "            } else if (symbol == (char) 9) {",
      "                out.append(backslash).append('t');",
      "            } else if (symbol == (char) 10) {",
      "                out.append(backslash).append('n');",
      "            } else if (symbol == (char) 12) {",
      "                out.append(backslash).append('f');",
      "            } else if (symbol == (char) 13) {",
      "                out.append(backslash).append('r');",
      "            } else if (symbol < (char) 32) {",
      '                String digits = "0123456789abcdef";',
      "                out.append(backslash).append('u').append('0').append('0');",
      "                out.append(digits.charAt((symbol >> 4) & 15)).append(digits.charAt(symbol & 15));",
      "            } else {",
      "                out.append(symbol);",
      "            }",
      "        }",
      "        out.append(quote);",
      "    }",
      "",
      "    private static void writeValue(StringBuilder out, Object value) {",
      "        if (value == null) {",
      '            out.append("null");',
      "            return;",
      "        }",
      "        if (value instanceof String) {",
      "            writeString(out, (String) value);",
      "            return;",
      "        }",
      "        if (value instanceof Boolean) {",
      '            out.append(((Boolean) value).booleanValue() ? "true" : "false");',
      "            return;",
      "        }",
      "        if (value instanceof Double || value instanceof Float) {",
      "            double number = ((Number) value).doubleValue();",
      "            if (Double.isNaN(number) || Double.isInfinite(number)) {",
      '                throw new IllegalStateException("Non-finite number");',
      "            }",
      "            out.append(Double.toString(number));",
      "            return;",
      "        }",
      "        if (value instanceof Number) {",
      "            out.append(value.toString());",
      "            return;",
      "        }",
      "        if (value instanceof java.util.Map) {",
      "            out.append('{');",
      "            boolean first = true;",
      "            for (java.util.Map.Entry<?, ?> entry : ((java.util.Map<?, ?>) value).entrySet()) {",
      "                if (!first) {",
      "                    out.append(',');",
      "                }",
      "                first = false;",
      "                writeString(out, String.valueOf(entry.getKey()));",
      "                out.append(':');",
      "                writeValue(out, entry.getValue());",
      "            }",
      "            out.append('}');",
      "            return;",
      "        }",
      "        if (value instanceof java.util.List) {",
      "            out.append('[');",
      "            boolean first = true;",
      "            for (Object item : (java.util.List<?>) value) {",
      "                if (!first) {",
      "                    out.append(',');",
      "                }",
      "                first = false;",
      "                writeValue(out, item);",
      "            }",
      "            out.append(']');",
      "            return;",
      "        }",
      "        writeString(out, String.valueOf(value));",
      "    }",
      "",
      "    static void Emit(String hypothesisId, String location, String message, Object data) {",
      "        try {",
      "            StringBuilder out = new StringBuilder();",
      "            out.append('{');",
      '            writeString(out, "hypothesisId");',
      "            out.append(':');",
      "            writeString(out, hypothesisId);",
      "            out.append(',');",
      '            writeString(out, "location");',
      "            out.append(':');",
      "            writeString(out, location);",
      "            out.append(',');",
      '            writeString(out, "message");',
      "            out.append(':');",
      "            writeString(out, message);",
      "            out.append(',');",
      '            writeString(out, "data");',
      "            out.append(':');",
      "            writeValue(out, redact(data, new java.util.IdentityHashMap<Object, Boolean>(), 0));",
      "            out.append(',');",
      '            writeString(out, "timestamp");',
      "            out.append(':');",
      "            out.append(System.currentTimeMillis());",
      "            out.append('}');",
      "            out.append((char) 10);",
      "            byte[] payload = out.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);",
      "            if (payload.length > 65536) {",
      "                return;",
      "            }",
      '            java.nio.file.Path path = java.nio.file.Paths.get("__APPEND_PATH__");',
      "            try {",
      '                java.nio.file.Files.createFile(path, java.nio.file.attribute.PosixFilePermissions.asFileAttribute(java.nio.file.attribute.PosixFilePermissions.fromString("rw-------")));',
      "            } catch (UnsupportedOperationException nonPosix) {",
      "                try {",
      "                    java.nio.file.Files.createFile(path);",
      "                } catch (Throwable ignored) {",
      "                }",
      "            } catch (Throwable ignored) {",
      "            }",
      "            java.nio.file.Files.write(path, payload, java.nio.file.StandardOpenOption.CREATE, java.nio.file.StandardOpenOption.APPEND);",
      "        } catch (Throwable failure) {",
      "            // Observations must never change application behavior.",
      "        }",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "java",
    dataEncoding: "native-json-value",
    placement: { call: "statement", helper: "top-level" },
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Java value that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
