import type { ProbeTemplates } from "./render";

export function renderJavaScriptTemplate(): ProbeTemplates {
  const helperTemplate = [
    "// #region agent log",
    "const __agentDebugIsSecretKey = (key) => {",
    "  const normalized = key",
    '    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")',
    '    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")',
    '    .replace(/[^a-zA-Z0-9]+/g, "_")',
    "    .toLowerCase()",
    '    .replace(/^_+|_+$/g, "");',
    "  return new Set([",
    '    "authorization", "authorization_header", "cookie", "set_cookie",',
    '    "password", "passwd", "pwd", "private_key", "secret", "token",',
    '    "credential", "credentials",',
    "  ]).has(normalized) ||",
    "    /(^|_)(api_key|api_token|oauth_token|o_auth_token|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token)$/.test(normalized);",
    "};",
    "",
    "const __agentDebugRedact = (value, active = new WeakSet(), depth = 0) => {",
    '  if (depth > 64) throw new Error("Observation graph is too deep");',
    '  if (value === null || typeof value !== "object") return value;',
    '  if (active.has(value)) throw new Error("Cyclic observation graph");',
    "  active.add(value);",
    "  try {",
    "    if (Array.isArray(value)) {",
    "      return value.map((item) => __agentDebugRedact(item, active, depth + 1));",
    "    }",
    "    return Object.fromEntries(",
    "      Object.entries(value).map(([key, item]) => [",
    "        key,",
    '        __agentDebugIsSecretKey(key) ? "[REDACTED]" : __agentDebugRedact(item, active, depth + 1),',
    "      ]),",
    "    );",
    "  } finally {",
    "    active.delete(value);",
    "  }",
    "};",
    "",
    "const __agentDebugEmit = (event) => {",
    "  try {",
    "    const payload = JSON.stringify({",
    "      ...event,",
    "      data: __agentDebugRedact(event.data),",
    "      timestamp: Date.now(),",
    '    }) + "\\n";',
    "    if (new TextEncoder().encode(payload).byteLength > 65_536) return;",
    '    void fetch("__INGEST_URL__", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/x-ndjson" },',
    "      body: payload,",
    "    })",
    "      .then(",
    "        (response) => {",
    "          try {",
    "            void response.body?.cancel().catch(() => undefined);",
    "          } catch {",
    "            // Response cleanup must never change application behavior.",
    "          }",
    "        },",
    "        () => undefined,",
    "      )",
    "      .catch(() => undefined);",
    "  } catch {",
    "    // Observations must never change application behavior.",
    "  }",
    "};",
    "// #endregion",
  ].join("\n");
  const callTemplate = [
    "// #region agent log",
    "__agentDebugEmit({",
    '  hypothesisId: "__HYPOTHESIS_ID__",',
    '  location: "__LOCATION__",',
    '  message: "__MESSAGE__",',
    "  data: __DATA_EXPRESSION__,",
    "});",
    "// #endregion",
  ].join("\n");
  return {
    callTemplate,
    helperTemplate,
    ingest: "http",
    language: "javascript",
    placeholders: {
      __DATA_EXPRESSION__:
        "Replace with a JSON-compatible JavaScript expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __INGEST_URL__: "Replace with the ingestUrl returned by debug-mode create.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
