import type { ProbeTemplates } from "./render";

export function renderKotlinTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      'AgentDebugLog.emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__)',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "object AgentDebugLog {",
      "    private val SECRET_KEYS = java.util.HashSet(java.util.Arrays.asList(",
      '        "authorization", "authorization_header", "cookie", "set_cookie",',
      '        "password", "passwd", "pwd", "private_key", "secret", "token",',
      '        "credential", "credentials"))',
      "",
      '    private val SECRET_BOUNDARY_ONE = java.util.regex.Pattern.compile("([A-Z]+)([A-Z][a-z])")',
      '    private val SECRET_BOUNDARY_TWO = java.util.regex.Pattern.compile("([a-z0-9])([A-Z])")',
      '    private val SECRET_NON_ALNUM = java.util.regex.Pattern.compile("[^a-zA-Z0-9]+")',
      '    private val SECRET_TRIM_LEADING = java.util.regex.Pattern.compile("^_+")',
      '    private val SECRET_TRIM_TRAILING = java.util.regex.Pattern.compile("_+\\$")',
      "    private val SECRET_SUFFIX = java.util.regex.Pattern.compile(",
      '        "(^|_)(api_key|api_token|oauth_token|o_auth_token|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token)\\$")',
      "",
      "    private fun isSecretKey(key: String): Boolean {",
      '        var normalized = SECRET_BOUNDARY_ONE.matcher(key).replaceAll("\\$1_\\$2")',
      '        normalized = SECRET_BOUNDARY_TWO.matcher(normalized).replaceAll("\\$1_\\$2")',
      '        normalized = SECRET_NON_ALNUM.matcher(normalized).replaceAll("_").lowercase()',
      '        normalized = SECRET_TRIM_LEADING.matcher(normalized).replaceAll("")',
      '        normalized = SECRET_TRIM_TRAILING.matcher(normalized).replaceAll("")',
      "        return SECRET_KEYS.contains(normalized) || SECRET_SUFFIX.matcher(normalized).find()",
      "    }",
      "",
      "    private fun decapitalize(name: String): String {",
      "        if (name.isEmpty()) {",
      "            return name",
      "        }",
      "        if (name.length > 1 && name[0].isUpperCase() && name[1].isUpperCase()) {",
      "            return name",
      "        }",
      "        val letters = name.toCharArray()",
      "        letters[0] = letters[0].lowercaseChar()",
      "        return String(letters)",
      "    }",
      "",
      "    private fun redact(value: Any?, active: java.util.IdentityHashMap<Any, Boolean>, depth: Int): Any? {",
      "        if (depth > 64) {",
      '            throw IllegalStateException("Observation graph is too deep")',
      "        }",
      "        if (value == null) {",
      "            return null",
      "        }",
      "        if (value is CharSequence || value is Char) {",
      "            return value.toString()",
      "        }",
      "        if (value is Number || value is Boolean) {",
      "            return value",
      "        }",
      "        if (value is Enum<*>) {",
      "            return value.name",
      "        }",
      "        if (active.put(value, true) != null) {",
      '            throw IllegalStateException("Cyclic observation graph")',
      "        }",
      "        try {",
      "            if (value is Map<*, *>) {",
      "                val redacted = java.util.LinkedHashMap<String, Any?>()",
      "                for (entry in value.entries) {",
      '                    val key = entry.key?.toString() ?: "null"',
      '                    redacted[key] = if (isSecretKey(key)) "[REDACTED]" else redact(entry.value, active, depth + 1)',
      "                }",
      "                return redacted",
      "            }",
      "            if (value is Iterable<*>) {",
      "                val redacted = java.util.ArrayList<Any?>()",
      "                for (item in value) {",
      "                    redacted.add(redact(item, active, depth + 1))",
      "                }",
      "                return redacted",
      "            }",
      "            if (value.javaClass.isArray) {",
      "                val redacted = java.util.ArrayList<Any?>()",
      "                val length = java.lang.reflect.Array.getLength(value)",
      "                for (index in 0 until length) {",
      "                    redacted.add(redact(java.lang.reflect.Array.get(value, index), active, depth + 1))",
      "                }",
      "                return redacted",
      "            }",
      "            val members = java.util.LinkedHashMap<String, Any?>()",
      "            val type = value.javaClass",
      "            for (method in type.methods) {",
      "                if (method.parameterCount != 0 || method.returnType == java.lang.Void.TYPE) {",
      "                    continue",
      "                }",
      "                if (java.lang.reflect.Modifier.isStatic(method.modifiers) || method.declaringClass == java.lang.Object::class.java) {",
      "                    continue",
      "                }",
      "                val name = method.name",
      "                val property: String",
      '                if (name.startsWith("get") && name.length > 3) {',
      "                    property = decapitalize(name.substring(3))",
      '                } else if (name.startsWith("is") && name.length > 2 && (method.returnType == java.lang.Boolean.TYPE || method.returnType == java.lang.Boolean::class.java)) {',
      "                    property = decapitalize(name.substring(2))",
      "                } else {",
      "                    continue",
      "                }",
      "                val raw: Any?",
      "                try {",
      "                    method.isAccessible = true",
      "                    raw = method.invoke(value)",
      "                } catch (methodFailure: Throwable) {",
      "                    continue",
      "                }",
      '                members[property] = if (isSecretKey(property)) "[REDACTED]" else redact(raw, active, depth + 1)',
      "            }",
      "            for (field in type.fields) {",
      "                if (java.lang.reflect.Modifier.isStatic(field.modifiers)) {",
      "                    continue",
      "                }",
      "                val raw: Any?",
      "                try {",
      "                    field.isAccessible = true",
      "                    raw = field.get(value)",
      "                } catch (fieldFailure: Throwable) {",
      "                    continue",
      "                }",
      '                members[field.name] = if (isSecretKey(field.name)) "[REDACTED]" else redact(raw, active, depth + 1)',
      "            }",
      "            return members",
      "        } finally {",
      "            active.remove(value)",
      "        }",
      "    }",
      "",
      "    private fun writeString(out: StringBuilder, text: String) {",
      "        val backslash = 92.toChar()",
      "        val quote = 34.toChar()",
      "        out.append(quote)",
      "        for (index in 0 until text.length) {",
      "            val symbol = text[index]",
      "            if (symbol == quote) {",
      "                out.append(backslash).append(quote)",
      "            } else if (symbol == backslash) {",
      "                out.append(backslash).append(backslash)",
      "            } else if (symbol == 8.toChar()) {",
      "                out.append(backslash).append('b')",
      "            } else if (symbol == 9.toChar()) {",
      "                out.append(backslash).append('t')",
      "            } else if (symbol == 10.toChar()) {",
      "                out.append(backslash).append('n')",
      "            } else if (symbol == 12.toChar()) {",
      "                out.append(backslash).append('f')",
      "            } else if (symbol == 13.toChar()) {",
      "                out.append(backslash).append('r')",
      "            } else if (symbol < 32.toChar()) {",
      '                val digits = "0123456789abcdef"',
      "                out.append(backslash).append('u').append('0').append('0')",
      "                out.append(digits[(symbol.code shr 4) and 15]).append(digits[symbol.code and 15])",
      "            } else {",
      "                out.append(symbol)",
      "            }",
      "        }",
      "        out.append(quote)",
      "    }",
      "",
      "    private fun writeValue(out: StringBuilder, value: Any?) {",
      "        if (value == null) {",
      '            out.append("null")',
      "            return",
      "        }",
      "        if (value is String) {",
      "            writeString(out, value)",
      "            return",
      "        }",
      "        if (value is Boolean) {",
      '            out.append(if (value) "true" else "false")',
      "            return",
      "        }",
      "        if (value is Double || value is Float) {",
      "            val number = (value as Number).toDouble()",
      "            if (number.isNaN() || number.isInfinite()) {",
      '                throw IllegalStateException("Non-finite number")',
      "            }",
      "            out.append(number.toString())",
      "            return",
      "        }",
      "        if (value is Number) {",
      "            out.append(value.toString())",
      "            return",
      "        }",
      "        if (value is Map<*, *>) {",
      "            out.append('{')",
      "            var first = true",
      "            for (entry in value.entries) {",
      "                if (!first) {",
      "                    out.append(',')",
      "                }",
      "                first = false",
      '                writeString(out, entry.key?.toString() ?: "null")',
      "                out.append(':')",
      "                writeValue(out, entry.value)",
      "            }",
      "            out.append('}')",
      "            return",
      "        }",
      "        if (value is List<*>) {",
      "            out.append('[')",
      "            var first = true",
      "            for (item in value) {",
      "                if (!first) {",
      "                    out.append(',')",
      "                }",
      "                first = false",
      "                writeValue(out, item)",
      "            }",
      "            out.append(']')",
      "            return",
      "        }",
      "        writeString(out, value.toString())",
      "    }",
      "",
      "    fun emit(hypothesisId: String, location: String, message: String, data: Any?) {",
      "        try {",
      "            val out = StringBuilder()",
      "            out.append('{')",
      '            writeString(out, "hypothesisId")',
      "            out.append(':')",
      "            writeString(out, hypothesisId)",
      "            out.append(',')",
      '            writeString(out, "location")',
      "            out.append(':')",
      "            writeString(out, location)",
      "            out.append(',')",
      '            writeString(out, "message")',
      "            out.append(':')",
      "            writeString(out, message)",
      "            out.append(',')",
      '            writeString(out, "data")',
      "            out.append(':')",
      "            writeValue(out, redact(data, java.util.IdentityHashMap<Any, Boolean>(), 0))",
      "            out.append(',')",
      '            writeString(out, "timestamp")',
      "            out.append(':')",
      "            out.append(System.currentTimeMillis())",
      "            out.append('}')",
      "            out.append(10.toChar())",
      "            val payload = out.toString().toByteArray(java.nio.charset.StandardCharsets.UTF_8)",
      "            if (payload.size > 65536) {",
      "                return",
      "            }",
      '            val path = java.nio.file.Paths.get("__APPEND_PATH__")',
      "            try {",
      '                java.nio.file.Files.createFile(path, java.nio.file.attribute.PosixFilePermissions.asFileAttribute(java.nio.file.attribute.PosixFilePermissions.fromString("rw-------")))',
      "            } catch (nonPosix: UnsupportedOperationException) {",
      "                try {",
      "                    java.nio.file.Files.createFile(path)",
      "                } catch (ignored: Throwable) {",
      "                }",
      "            } catch (ignored: Throwable) {",
      "            }",
      "            java.nio.file.Files.write(path, payload, java.nio.file.StandardOpenOption.CREATE, java.nio.file.StandardOpenOption.APPEND)",
      "        } catch (failure: Throwable) {",
      "            // Observations must never change application behavior.",
      "        }",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "kotlin",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Kotlin value that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
