import type { ProbeTemplates } from "./render";

export function renderPhpTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      '__agentDebugEmit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "function __agentDebugIsSecretKey(string $key): bool",
      "{",
      "    $normalized = preg_replace('/([A-Z]+)([A-Z][a-z])/', '$1_$2', $key);",
      "    $normalized = preg_replace('/([a-z0-9])([A-Z])/', '$1_$2', $normalized ?? '');",
      '    $normalized = preg_replace("/[^a-zA-Z0-9]+/", "_", $normalized ?? "");',
      '    $normalized = trim(strtolower($normalized ?? ""), "_");',
      "    return in_array($normalized, [",
      '        "authorization", "authorization_header", "cookie", "set_cookie",',
      '        "password", "passwd", "pwd", "private_key", "secret", "token",',
      '        "credential", "credentials",',
      "    ], true) || preg_match(",
      '        "/(^|_)(password|passwd|pwd|secret|token|api_key|api_token|oauth_token|o_auth_token|authorization|authorization_header|cookie|set_cookie|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token|credential|credentials)$/",',
      "        $normalized,",
      "    ) === 1;",
      "}",
      "",
      "function __agentDebugRedact(mixed $value, ?SplObjectStorage $active = null, int $depth = 0): mixed",
      "{",
      "    if ($depth > 64) {",
      '        throw new RuntimeException("Observation graph is too deep");',
      "    }",
      "    $active ??= new SplObjectStorage();",
      "    if (is_object($value)) {",
      "        if ($active->contains($value)) {",
      '            throw new RuntimeException("Cyclic observation graph");',
      "        }",
      "        $active->attach($value);",
      "        try {",
      "            return __agentDebugRedact(get_object_vars($value), $active, $depth + 1);",
      "        } finally {",
      "            $active->detach($value);",
      "        }",
      "    }",
      "    if (!is_array($value)) {",
      "        return $value;",
      "    }",
      "    $redacted = [];",
      "    foreach ($value as $key => $item) {",
      "        $redacted[$key] = is_string($key) && __agentDebugIsSecretKey($key)",
      '            ? "[REDACTED]"',
      "            : __agentDebugRedact($item, $active, $depth + 1);",
      "    }",
      "    return $redacted;",
      "}",
      "",
      "function __agentDebugEmit(string $hypothesisId, string $location, string $message, mixed $data): void",
      "{",
      "    try {",
      "        $payload = json_encode([",
      '            "hypothesisId" => $hypothesisId,',
      '            "location" => $location,',
      '            "message" => $message,',
      '            "data" => __agentDebugRedact($data),',
      '            "timestamp" => (int) floor(microtime(true) * 1000),',
      '        ], JSON_THROW_ON_ERROR) . "\\n";',
      "        if (strlen($payload) > 65_536) {",
      "            return;",
      "        }",
      '        @file_put_contents("__APPEND_PATH__", $payload, FILE_APPEND | LOCK_EX);',
      "    } catch (Throwable) {",
      "        // Observations must never change application behavior.",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "php",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible PHP expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
