import type { ProbeTemplates } from "./render";

export function renderPowerShellTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "# region agent log",
      'Write-AgentDebugEvent "__HYPOTHESIS_ID__" "__LOCATION__" "__MESSAGE__" (__DATA_EXPRESSION__)',
      "# endregion",
    ].join("\n"),
    helperTemplate: [
      "# region agent log",
      "function Test-AgentDebugSecretKey {",
      "    param([string] $Key)",
      "    $normalized = $Key -creplace '([A-Z]+)([A-Z][a-z])', '$1_$2'",
      "    $normalized = $normalized -creplace '([a-z0-9])([A-Z])', '$1_$2'",
      "    $normalized = (($normalized -replace '[^a-zA-Z0-9]+', '_').ToLower()).Trim('_')",
      "    $secretKeys = @(",
      "        'authorization', 'authorization_header', 'cookie', 'set_cookie',",
      "        'password', 'passwd', 'pwd', 'private_key', 'secret', 'token',",
      "        'credential', 'credentials'",
      "    )",
      "    return $secretKeys -contains $normalized -or",
      "        $normalized -match '(^|_)(password|passwd|pwd|secret|token|api_key|api_token|oauth_token|o_auth_token|authorization|authorization_header|cookie|set_cookie|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token|credential|credentials)$'",
      "}",
      "",
      "function Protect-AgentDebugValue {",
      "    param(",
      "        [object] $Value,",
      "        [Collections.Generic.HashSet[object]] $Active = [Collections.Generic.HashSet[object]]::new([Collections.Generic.ReferenceEqualityComparer]::Instance),",
      "        [int] $Depth = 0",
      "    )",
      "    if ($Depth -gt 64) { throw 'Observation graph is too deep' }",
      "    if ($null -eq $Value -or $Value -is [string] -or $Value -is [ValueType]) {",
      "        return $Value",
      "    }",
      "    if (-not $Active.Add($Value)) { throw 'Cyclic observation graph' }",
      "    try {",
      "        if ($Value -is [Collections.IDictionary]) {",
      "            $redacted = [ordered]@{}",
      "            foreach ($key in $Value.Keys) {",
      "                $redacted[$key] = if (Test-AgentDebugSecretKey ([string] $key)) {",
      "                    '[REDACTED]'",
      "                } else {",
      "                    Protect-AgentDebugValue ($Value[$key]) $Active ($Depth + 1)",
      "                }",
      "            }",
      "            return $redacted",
      "        }",
      "        if ($Value -is [Collections.IEnumerable]) {",
      "            $redacted = @($Value | ForEach-Object {",
      "                Protect-AgentDebugValue $_ $Active ($Depth + 1)",
      "            })",
      "            return ,$redacted",
      "        }",
      "        $redacted = [ordered]@{}",
      "        foreach ($property in $Value.PSObject.Properties) {",
      "            $redacted[$property.Name] = if (Test-AgentDebugSecretKey $property.Name) {",
      "                '[REDACTED]'",
      "            } else {",
      "                Protect-AgentDebugValue $property.Value $Active ($Depth + 1)",
      "            }",
      "        }",
      "        return $redacted",
      "    } finally {",
      "        [void] $Active.Remove($Value)",
      "    }",
      "}",
      "",
      "function Write-AgentDebugEvent {",
      "    param(",
      "        [string] $HypothesisId,",
      "        [string] $Location,",
      "        [string] $Message,",
      "        [object] $Data",
      "    )",
      "    try {",
      "        $eventData = [ordered]@{",
      "            hypothesisId = $HypothesisId",
      "            location = $Location",
      "            message = $Message",
      "            data = (Protect-AgentDebugValue $Data)",
      "            timestamp = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()",
      "        }",
      '        $json = ($eventData | ConvertTo-Json -Compress -Depth 8 -ErrorAction Stop -WarningAction SilentlyContinue) + "`n"',
      "        $bytes = [Text.UTF8Encoding]::new($false).GetBytes($json)",
      "        if ($bytes.Length -gt 65_536) { return }",
      '        $stream = [IO.File]::Open("__APPEND_PATH__", [IO.FileMode]::Append, [IO.FileAccess]::Write, [IO.FileShare]::ReadWrite)',
      "        try {",
      "            $stream.Write($bytes, 0, $bytes.Length)",
      "        } finally {",
      "            $stream.Dispose()",
      "        }",
      "    } catch {",
      "        # Observations must never change application behavior.",
      "    }",
      "}",
      "# endregion",
    ].join("\n"),
    ingest: "file",
    language: "powershell",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__:
        "Replace with a JSON-compatible PowerShell expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
