import type { ProbeTemplates } from "./render";

export function renderPythonTemplate(): ProbeTemplates {
  const helperTemplate = [
    "# region agent log",
    "import json",
    "import os",
    "import re",
    "import time",
    "",
    "__agent_debug_secret_keys = frozenset({",
    '    "authorization", "authorization_header", "cookie", "set_cookie",',
    '    "password", "passwd", "pwd", "private_key", "secret", "token",',
    '    "credential", "credentials",',
    "})",
    "",
    "def __agent_debug_is_secret_key(key):",
    '    normalized = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\\1_\\2", str(key))',
    '    normalized = re.sub(r"([a-z0-9])([A-Z])", r"\\1_\\2", normalized)',
    '    normalized = re.sub(r"[^a-zA-Z0-9]+", "_", normalized).lower().strip("_")',
    "    return normalized in __agent_debug_secret_keys or re.search(",
    '        r"(^|_)(password|passwd|pwd|secret|token|api_key|api_token|oauth_token|o_auth_token|authorization|authorization_header|cookie|set_cookie|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token|credential|credentials)$",',
    "        normalized,",
    "    ) is not None",
    "",
    "def __agent_debug_redact(value, active=None, depth=0):",
    "    if depth > 64:",
    '        raise ValueError("Observation graph is too deep")',
    "    if not isinstance(value, (list, tuple, dict)):",
    "        return value",
    "    if active is None:",
    "        active = set()",
    "    identity = id(value)",
    "    if identity in active:",
    '        raise ValueError("Cyclic observation graph")',
    "    active.add(identity)",
    "    try:",
    "        if isinstance(value, (list, tuple)):",
    "            return [__agent_debug_redact(item, active, depth + 1) for item in value]",
    "        return {",
    '            key: "[REDACTED]"',
    "            if __agent_debug_is_secret_key(key)",
    "            else __agent_debug_redact(item, active, depth + 1)",
    "            for key, item in value.items()",
    "        }",
    "    finally:",
    "        active.remove(identity)",
    "",
    "def __agent_debug_emit(hypothesis_id, location, message, data):",
    "    try:",
    "        payload = json.dumps(",
    "            {",
    '                "hypothesisId": hypothesis_id,',
    '                "location": location,',
    '                "message": message,',
    '                "data": __agent_debug_redact(data),',
    '                "timestamp": int(time.time() * 1000),',
    "            },",
    "            allow_nan=False,",
    '            separators=(",", ":"),',
    '        ).encode("utf-8") + b"\\n"',
    "        if len(payload) > 65_536:",
    "            return",
    '        descriptor = os.open("__APPEND_PATH__", os.O_APPEND | os.O_CREAT | os.O_WRONLY, 0o600)',
    "        try:",
    "            os.write(descriptor, payload)",
    "        finally:",
    "            os.close(descriptor)",
    "    except Exception:",
    "        pass",
    "# endregion",
  ].join("\n");
  const callTemplate = [
    "# region agent log",
    "__agent_debug_emit(",
    '    "__HYPOTHESIS_ID__",',
    '    "__LOCATION__",',
    '    "__MESSAGE__",',
    "    __DATA_EXPRESSION__,",
    ")",
    "# endregion",
  ].join("\n");
  return {
    callTemplate,
    helperTemplate,
    ingest: "file",
    language: "python",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Python expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
