import type { ProbeTemplates } from "./render";

export function renderRubyTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "# region agent log",
      '__agent_debug_emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__)',
      "# endregion",
    ].join("\n"),
    helperTemplate: [
      "# region agent log",
      'require "json"',
      "",
      "AGENT_DEBUG_SECRET_KEYS = [",
      '  "authorization", "authorization_header", "cookie", "set_cookie",',
      '  "password", "passwd", "pwd", "private_key", "secret", "token",',
      '  "credential", "credentials"',
      "].freeze",
      "",
      "def __agent_debug_secret_key?(key)",
      '  normalized = key.to_s.gsub(/([a-z0-9])([A-Z])/, "\\\\1_\\\\2")',
      '  normalized = normalized.gsub(/[^a-zA-Z0-9]+/, "_").downcase.gsub(/^_+|_+$/, "")',
      "  AGENT_DEBUG_SECRET_KEYS.include?(normalized) ||",
      "    /(^|_)(password|passwd|pwd|secret|token|api_key|authorization|authorization_header|cookie|set_cookie|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token|credential|credentials)$/.match?(normalized)",
      "end",
      "",
      "def __agent_debug_redact(value)",
      "  case value",
      "  when Array",
      "    value.map { |item| __agent_debug_redact(item) }",
      "  when Hash",
      '    value.to_h { |key, item| [key, __agent_debug_secret_key?(key) ? "[REDACTED]" : __agent_debug_redact(item)] }',
      "  else",
      "    value",
      "  end",
      "end",
      "",
      "def __agent_debug_emit(hypothesis_id, location, message, data)",
      "  payload = JSON.generate(",
      "    hypothesisId: hypothesis_id,",
      "    location: location,",
      "    message: message,",
      "    data: __agent_debug_redact(data),",
      "    timestamp: (Time.now.to_f * 1000).to_i",
      '  ).encode("UTF-8") + "\\n"',
      "  return if payload.bytesize > 65_536",
      '  File.open("__APPEND_PATH__", "ab", 0o600) { |file| file.write(payload) }',
      "rescue StandardError",
      "  nil",
      "end",
      "# endregion",
    ].join("\n"),
    ingest: "file",
    language: "ruby",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Ruby expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
