import type { ProbeTemplates } from "./render";

export function renderRubyTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "# region agent log",
      '__agent_debug_emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__)',
      "# endregion",
    ].join("\n"),
    helperTemplate: [
      "# region agent log",
      'require "json"',
      "",
      "AGENT_DEBUG_SECRET_KEYS = [",
      '  "authorization", "authorization_header", "cookie", "set_cookie",',
      '  "password", "passwd", "pwd", "private_key", "secret", "token",',
      '  "credential", "credentials"',
      "].freeze",
      "",
      "def __agent_debug_secret_key?(key)",
      '  normalized = key.to_s.gsub(/([A-Z]+)([A-Z][a-z])/, "\\\\1_\\\\2")',
      '  normalized = normalized.gsub(/([a-z0-9])([A-Z])/, "\\\\1_\\\\2")',
      '  normalized = normalized.gsub(/[^a-zA-Z0-9]+/, "_").downcase.gsub(/^_+|_+$/, "")',
      "  AGENT_DEBUG_SECRET_KEYS.include?(normalized) ||",
      "    /(^|_)(api_key|api_token|oauth_token|o_auth_token|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token)$/.match?(normalized)",
      "end",
      "",
      "def __agent_debug_redact(value, active = {}, depth = 0)",
      '  raise ArgumentError, "Observation graph is too deep" if depth > 64',
      "  return value unless value.is_a?(Array) || value.is_a?(Hash)",
      "  identity = value.object_id",
      '  raise ArgumentError, "Cyclic observation graph" if active.key?(identity)',
      "  active[identity] = true",
      "  begin",
      "    case value",
      "    when Array",
      "      value.map { |item| __agent_debug_redact(item, active, depth + 1) }",
      "    when Hash",
      '      value.to_h { |key, item| [key, __agent_debug_secret_key?(key) ? "[REDACTED]" : __agent_debug_redact(item, active, depth + 1)] }',
      "    end",
      "  ensure",
      "    active.delete(identity)",
      "  end",
      "end",
      "",
      "def __agent_debug_emit(hypothesis_id, location, message, data)",
      "  payload = JSON.generate(",
      "    hypothesisId: hypothesis_id,",
      "    location: location,",
      "    message: message,",
      "    data: __agent_debug_redact(data),",
      "    timestamp: (Time.now.to_f * 1000).to_i",
      '  ).encode("UTF-8") + "\\n"',
      "  return if payload.bytesize > 65_536",
      '  File.open("__APPEND_PATH__", "ab", 0o600) { |file| file.write(payload) }',
      "rescue StandardError",
      "  nil",
      "end",
      "# endregion",
    ].join("\n"),
    ingest: "file",
    language: "ruby",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Ruby expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
