import type { ProbeTemplates } from "./render";

export function renderRustTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      '__agentDebugEmit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "#[derive(Clone)]",
      "#[allow(dead_code)]",
      "enum AgentValue {",
      "    Null,",
      "    Bool(bool),",
      "    Int(i64),",
      "    Float(f64),",
      "    Str(String),",
      "    Array(Vec<AgentValue>),",
      "    Object(Vec<(String, AgentValue)>),",
      "}",
      "",
      "impl From<bool> for AgentValue { fn from(value: bool) -> Self { AgentValue::Bool(value) } }",
      "impl From<i64> for AgentValue { fn from(value: i64) -> Self { AgentValue::Int(value) } }",
      "impl From<f64> for AgentValue { fn from(value: f64) -> Self { AgentValue::Float(value) } }",
      "impl From<&str> for AgentValue { fn from(value: &str) -> Self { AgentValue::Str(value.to_string()) } }",
      "impl From<String> for AgentValue { fn from(value: String) -> Self { AgentValue::Str(value) } }",
      "",
      "macro_rules! adbg {",
      "    ({ $($key:tt : $value:tt),* $(,)? }) => {",
      "        AgentValue::Object(vec![ $( ($key.to_string(), adbg!($value)) ),* ])",
      "    };",
      "    ([ $($value:tt),* $(,)? ]) => {",
      "        AgentValue::Array(vec![ $( adbg!($value) ),* ])",
      "    };",
      "    ($other:expr) => {",
      "        AgentValue::from($other)",
      "    };",
      "}",
      "",
      "const AGENT_DEBUG_SECRET_KEYS: [&str; 12] = [",
      '    "authorization", "authorization_header", "cookie", "set_cookie",',
      '    "password", "passwd", "pwd", "private_key", "secret", "token",',
      '    "credential", "credentials",',
      "];",
      "",
      "const AGENT_DEBUG_SECRET_SUFFIXES: [&str; 11] = [",
      '    "api_key", "api_token", "oauth_token", "o_auth_token", "private_key",',
      '    "client_secret", "access_token", "refresh_token", "id_token",',
      '    "auth_token", "bearer_token",',
      "];",
      "",
      "fn __agent_debug_split_acronym(input: &str) -> String {",
      "    let chars: Vec<char> = input.chars().collect();",
      "    let mut result = String::new();",
      "    let mut i = 0;",
      "    while i < chars.len() {",
      "        if chars[i].is_ascii_uppercase() {",
      "            let mut j = i;",
      "            while j < chars.len() && chars[j].is_ascii_uppercase() {",
      "                j += 1;",
      "            }",
      "            if j - i >= 2 && j < chars.len() && chars[j].is_ascii_lowercase() {",
      "                for k in i..(j - 1) {",
      "                    result.push(chars[k]);",
      "                }",
      "                result.push('_');",
      "                result.push(chars[j - 1]);",
      "                result.push(chars[j]);",
      "                i = j + 1;",
      "                continue;",
      "            }",
      "            for k in i..j {",
      "                result.push(chars[k]);",
      "            }",
      "            i = j;",
      "            continue;",
      "        }",
      "        result.push(chars[i]);",
      "        i += 1;",
      "    }",
      "    result",
      "}",
      "",
      "fn __agent_debug_split_camel(input: &str) -> String {",
      "    let chars: Vec<char> = input.chars().collect();",
      "    let mut result = String::new();",
      "    let mut i = 0;",
      "    while i < chars.len() {",
      "        result.push(chars[i]);",
      "        let boundary = chars[i].is_ascii_lowercase() || chars[i].is_ascii_digit();",
      "        if boundary && i + 1 < chars.len() && chars[i + 1].is_ascii_uppercase() {",
      "            result.push('_');",
      "        }",
      "        i += 1;",
      "    }",
      "    result",
      "}",
      "",
      "fn __agent_debug_normalize_key(key: &str) -> String {",
      "    let split = __agent_debug_split_camel(&__agent_debug_split_acronym(key));",
      "    let mut normalized = String::new();",
      "    let mut pending_underscore = false;",
      "    for c in split.chars() {",
      "        if c.is_ascii_alphanumeric() {",
      "            if pending_underscore && !normalized.is_empty() {",
      "                normalized.push('_');",
      "            }",
      "            pending_underscore = false;",
      "            for lower in c.to_lowercase() {",
      "                normalized.push(lower);",
      "            }",
      "        } else {",
      "            pending_underscore = true;",
      "        }",
      "    }",
      "    normalized",
      "}",
      "",
      "fn __agent_debug_is_secret_key(key: &str) -> bool {",
      "    let normalized = __agent_debug_normalize_key(key);",
      "    for exact in AGENT_DEBUG_SECRET_KEYS.iter() {",
      "        if normalized == *exact {",
      "            return true;",
      "        }",
      "    }",
      "    let bytes = normalized.as_bytes();",
      "    for suffix in AGENT_DEBUG_SECRET_SUFFIXES.iter() {",
      "        if normalized.ends_with(suffix) {",
      "            let boundary = normalized.len() - suffix.len();",
      "            if boundary == 0 || bytes[boundary - 1] == b'_' {",
      "                return true;",
      "            }",
      "        }",
      "    }",
      "    false",
      "}",
      "",
      "fn __agent_debug_write_string(out: &mut String, text: &str) {",
      "    let backslash = char::from(92u8);",
      "    let quote = char::from(34u8);",
      "    out.push(quote);",
      "    for c in text.chars() {",
      "        let code = c as u32;",
      "        if c == quote {",
      "            out.push(backslash);",
      "            out.push(quote);",
      "        } else if c == backslash {",
      "            out.push(backslash);",
      "            out.push(backslash);",
      "        } else if code == 8 {",
      "            out.push(backslash);",
      "            out.push(char::from(98u8));",
      "        } else if code == 9 {",
      "            out.push(backslash);",
      "            out.push(char::from(116u8));",
      "        } else if code == 10 {",
      "            out.push(backslash);",
      "            out.push(char::from(110u8));",
      "        } else if code == 12 {",
      "            out.push(backslash);",
      "            out.push(char::from(102u8));",
      "        } else if code == 13 {",
      "            out.push(backslash);",
      "            out.push(char::from(114u8));",
      "        } else if code < 32 {",
      '            let digits = "0123456789abcdef".as_bytes();',
      "            out.push(backslash);",
      "            out.push(char::from(117u8));",
      "            out.push(char::from(48u8));",
      "            out.push(char::from(48u8));",
      "            out.push(char::from(digits[((code >> 4) & 15) as usize]));",
      "            out.push(char::from(digits[(code & 15) as usize]));",
      "        } else {",
      "            out.push(c);",
      "        }",
      "    }",
      "    out.push(quote);",
      "}",
      "",
      "fn __agent_debug_write_value(out: &mut String, value: &AgentValue, depth: usize) -> bool {",
      "    if depth > 64 {",
      "        return false;",
      "    }",
      "    match value {",
      '        AgentValue::Null => out.push_str("null"),',
      '        AgentValue::Bool(flag) => out.push_str(if *flag { "true" } else { "false" }),',
      "        AgentValue::Int(number) => out.push_str(&number.to_string()),",
      "        AgentValue::Float(number) => {",
      "            if !number.is_finite() {",
      "                return false;",
      "            }",
      "            out.push_str(&number.to_string());",
      "        }",
      "        AgentValue::Str(text) => __agent_debug_write_string(out, text),",
      "        AgentValue::Array(items) => {",
      "            out.push('[');",
      "            let mut index = 0;",
      "            for item in items.iter() {",
      "                if index > 0 {",
      "                    out.push(',');",
      "                }",
      "                index += 1;",
      "                if !__agent_debug_write_value(out, item, depth + 1) {",
      "                    return false;",
      "                }",
      "            }",
      "            out.push(']');",
      "        }",
      "        AgentValue::Object(entries) => {",
      "            out.push('{');",
      "            let mut index = 0;",
      "            for entry in entries.iter() {",
      "                if index > 0 {",
      "                    out.push(',');",
      "                }",
      "                index += 1;",
      "                __agent_debug_write_string(out, &entry.0);",
      "                out.push(':');",
      "                if __agent_debug_is_secret_key(&entry.0) {",
      '                    __agent_debug_write_string(out, "[REDACTED]");',
      "                } else if !__agent_debug_write_value(out, &entry.1, depth + 1) {",
      "                    return false;",
      "                }",
      "            }",
      "            out.push('}');",
      "        }",
      "    }",
      "    true",
      "}",
      "",
      "fn __agent_debug_timestamp_ms() -> i64 {",
      "    match std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH) {",
      "        Ok(elapsed) => elapsed.as_millis() as i64,",
      "        Err(_) => 0,",
      "    }",
      "}",
      "",
      "#[allow(non_snake_case)]",
      "fn __agentDebugEmit(hypothesis_id: &str, location: &str, message: &str, data: AgentValue) {",
      "    let mut out = String::new();",
      "    out.push('{');",
      '    __agent_debug_write_string(&mut out, "hypothesisId");',
      "    out.push(':');",
      "    __agent_debug_write_string(&mut out, hypothesis_id);",
      "    out.push(',');",
      '    __agent_debug_write_string(&mut out, "location");',
      "    out.push(':');",
      "    __agent_debug_write_string(&mut out, location);",
      "    out.push(',');",
      '    __agent_debug_write_string(&mut out, "message");',
      "    out.push(':');",
      "    __agent_debug_write_string(&mut out, message);",
      "    out.push(',');",
      '    __agent_debug_write_string(&mut out, "data");',
      "    out.push(':');",
      "    if !__agent_debug_write_value(&mut out, &data, 0) {",
      "        return;",
      "    }",
      "    out.push(',');",
      '    __agent_debug_write_string(&mut out, "timestamp");',
      "    out.push(':');",
      "    out.push_str(&__agent_debug_timestamp_ms().to_string());",
      "    out.push('}');",
      "    out.push(char::from(10u8));",
      "    if out.len() > 65536 {",
      "        return;",
      "    }",
      "    let mut options = std::fs::OpenOptions::new();",
      "    options.create(true).append(true);",
      "    #[cfg(unix)]",
      "    {",
      "        use std::os::unix::fs::OpenOptionsExt;",
      "        options.mode(0o600);",
      "    }",
      '    if let Ok(mut file) = options.open("__APPEND_PATH__") {',
      "        use std::io::Write;",
      "        let _ = file.write_all(out.as_bytes());",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "rust",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Rust AgentValue that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
