import type { ProbeTemplates } from "./render";

export function renderRustTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      'agent_debug_mode::emit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_JSON_EXPRESSION__);',
      "// #endregion",
    ].join("\n"),
    dataEncoding: "serialized-json",
    helperTemplate: [
      "// #region agent log",
      "#[allow(dead_code)]",
      "mod agent_debug_mode {",
      "    pub fn json_string(text: &str) -> String {",
      "        let backslash = char::from(92u8);",
      "        let quote = char::from(34u8);",
      "        let mut out = String::new();",
      "        out.push(quote);",
      "        for c in text.chars() {",
      "            let code = c as u32;",
      "            if c == quote {",
      "                out.push(backslash);",
      "                out.push(quote);",
      "            } else if c == backslash {",
      "                out.push(backslash);",
      "                out.push(backslash);",
      "            } else if code == 8 {",
      "                out.push(backslash);",
      "                out.push(char::from(98u8));",
      "            } else if code == 9 {",
      "                out.push(backslash);",
      "                out.push(char::from(116u8));",
      "            } else if code == 10 {",
      "                out.push(backslash);",
      "                out.push(char::from(110u8));",
      "            } else if code == 12 {",
      "                out.push(backslash);",
      "                out.push(char::from(102u8));",
      "            } else if code == 13 {",
      "                out.push(backslash);",
      "                out.push(char::from(114u8));",
      "            } else if code < 32 {",
      '                let digits = "0123456789abcdef".as_bytes();',
      "                out.push(backslash);",
      "                out.push(char::from(117u8));",
      "                out.push(char::from(48u8));",
      "                out.push(char::from(48u8));",
      "                out.push(char::from(digits[((code >> 4) & 15) as usize]));",
      "                out.push(char::from(digits[(code & 15) as usize]));",
      "            } else {",
      "                out.push(c);",
      "            }",
      "        }",
      "        out.push(quote);",
      "        out",
      "    }",
      "",
      "    fn timestamp_ms() -> i64 {",
      "        match std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH) {",
      "            Ok(elapsed) => elapsed.as_millis() as i64,",
      "            Err(_) => 0,",
      "        }",
      "    }",
      "",
      "    pub fn emit(hypothesis_id: &str, location: &str, message: &str, data_json: &str) {",
      "        if data_json.is_empty() {",
      "            return;",
      "        }",
      "        let mut out = String::new();",
      "        out.push('{');",
      '        out.push_str(&json_string("hypothesisId"));',
      "        out.push(':');",
      "        out.push_str(&json_string(hypothesis_id));",
      "        out.push(',');",
      '        out.push_str(&json_string("location"));',
      "        out.push(':');",
      "        out.push_str(&json_string(location));",
      "        out.push(',');",
      '        out.push_str(&json_string("message"));',
      "        out.push(':');",
      "        out.push_str(&json_string(message));",
      "        out.push(',');",
      '        out.push_str(&json_string("data"));',
      "        out.push(':');",
      "        out.push_str(data_json);",
      "        out.push(',');",
      '        out.push_str(&json_string("timestamp"));',
      "        out.push(':');",
      "        out.push_str(&timestamp_ms().to_string());",
      "        out.push('}');",
      "        out.push(char::from(10u8));",
      "        if out.len() > 65536 {",
      "            return;",
      "        }",
      "        let mut options = std::fs::OpenOptions::new();",
      "        options.create(true).append(true);",
      "        #[cfg(unix)]",
      "        {",
      "            use std::os::unix::fs::OpenOptionsExt;",
      "            options.mode(0o600);",
      "        }",
      '        if let Ok(mut file) = options.open("__APPEND_PATH__") {',
      "            use std::io::Write;",
      "            let _ = file.write_all(out.as_bytes());",
      "        }",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "rust",
    placement: { call: "statement", helper: "top-level" },
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_JSON_EXPRESSION__:
        "Replace with an expression that returns one complete valid JSON value containing no secrets. Use the application's serializer when available; otherwise pass agent_debug_mode::json_string(text).",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
