import type { ProbeTemplates } from "./render";

export function renderSwiftTemplate(): ProbeTemplates {
  return {
    callTemplate: [
      "// #region agent log",
      '__agentDebugEmit("__HYPOTHESIS_ID__", "__LOCATION__", "__MESSAGE__", __DATA_EXPRESSION__)',
      "// #endregion",
    ].join("\n"),
    helperTemplate: [
      "// #region agent log",
      "import Foundation",
      "#if canImport(Darwin)",
      "import Darwin",
      "#elseif canImport(Glibc)",
      "import Glibc",
      "#endif",
      "",
      "let __agentDebugSecretKeys: Set<String> = [",
      '    "authorization", "authorization_header", "cookie", "set_cookie",',
      '    "password", "passwd", "pwd", "private_key", "secret", "token",',
      '    "credential", "credentials",',
      "]",
      "",
      "func __agentDebugIsSecretKey(_ key: String) -> Bool {",
      '    var normalized = key.replacingOccurrences(of: "([A-Z]+)([A-Z][a-z])", with: "$1_$2", options: .regularExpression)',
      '    normalized = normalized.replacingOccurrences(of: "([a-z0-9])([A-Z])", with: "$1_$2", options: .regularExpression)',
      '    normalized = normalized.replacingOccurrences(of: "[^a-zA-Z0-9]+", with: "_", options: .regularExpression)',
      '        .lowercased().trimmingCharacters(in: CharacterSet(charactersIn: "_"))',
      "    if __agentDebugSecretKeys.contains(normalized) { return true }",
      '    return normalized.range(of: "(^|_)(password|passwd|pwd|secret|token|api_key|api_token|oauth_token|o_auth_token|authorization|authorization_header|cookie|set_cookie|private_key|client_secret|access_token|refresh_token|id_token|auth_token|bearer_token|credential|credentials)$", options: .regularExpression) != nil',
      "}",
      "",
      "func __agentDebugRedact(_ value: Any) throws -> Any {",
      "    var active = Set<ObjectIdentifier>()",
      "    return try __agentDebugRedactValue(value, active: &active, depth: 0)",
      "}",
      "",
      "func __agentDebugRedactValue(_ value: Any, active: inout Set<ObjectIdentifier>, depth: Int) throws -> Any {",
      '    guard depth <= 64 else { throw NSError(domain: "AgentDebug", code: 1) }',
      "    let mirror = Mirror(reflecting: value)",
      "    var identity: ObjectIdentifier?",
      "    if mirror.displayStyle == .class {",
      "        let candidate = ObjectIdentifier(value as AnyObject)",
      '        guard !active.contains(candidate) else { throw NSError(domain: "AgentDebug", code: 2) }',
      "        active.insert(candidate)",
      "        identity = candidate",
      "    }",
      "    defer { if let identity { active.remove(identity) } }",
      "    if let array = value as? [Any] {",
      "        return try array.map { try __agentDebugRedactValue($0, active: &active, depth: depth + 1) }",
      "    }",
      "    if let dictionary = value as? [String: Any] {",
      "        var redacted: [String: Any] = [:]",
      "        for (key, item) in dictionary {",
      '            redacted[key] = __agentDebugIsSecretKey(key) ? "[REDACTED]" : try __agentDebugRedactValue(item, active: &active, depth: depth + 1)',
      "        }",
      "        return redacted",
      "    }",
      "    return value",
      "}",
      "",
      "func __agentDebugEmit(_ hypothesisId: String, _ location: String, _ message: String, _ data: Any) {",
      "    do {",
      "        let event: [String: Any] = [",
      '            "hypothesisId": hypothesisId,',
      '            "location": location,',
      '            "message": message,',
      '            "data": try __agentDebugRedact(data),',
      '            "timestamp": Int64(Date().timeIntervalSince1970 * 1000),',
      "        ]",
      "        var payload = try JSONSerialization.data(withJSONObject: event)",
      "        payload.append(0x0A)",
      "        guard payload.count <= 65_536 else { return }",
      '        let descriptor = open("__APPEND_PATH__", O_WRONLY | O_APPEND | O_CREAT, mode_t(0o600))',
      "        guard descriptor >= 0 else { return }",
      "        defer { _ = close(descriptor) }",
      "        payload.withUnsafeBytes { buffer in",
      "            guard let baseAddress = buffer.baseAddress else { return }",
      "            let written = write(descriptor, baseAddress, buffer.count)",
      "            guard written == buffer.count else { return }",
      "        }",
      "    } catch {",
      "        // Observations must never change application behavior.",
      "    }",
      "}",
      "// #endregion",
    ].join("\n"),
    ingest: "file",
    language: "swift",
    placeholders: {
      __APPEND_PATH__: "Replace with the appendPath returned by debug-mode create.",
      __DATA_EXPRESSION__: "Replace with a JSON-compatible Swift expression that has no secrets.",
      __HYPOTHESIS_ID__: "Replace with the hypothesis label.",
      __LOCATION__: "Replace with the observed source location.",
      __MESSAGE__: "Replace with a constant observation message.",
    },
  };
}
